### ISSUE TITLE
Data is compressed as lz4 but we don't have this installed

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#157]
I'm trying to read the Zarr data I wrote using this code:
https://github.com/pangeo-data/pangeo/issues/155#issuecomment-372793428

but I'm getting:
```
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/home/jovyan/my-conda-envs/IOOS/lib/python3.6/site-packages/distributed/protocol/core.py", line 167, in loads_msgpack
    decompress = compressions[header['compression']]['decompress']
KeyError: 'lz4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jovyan/my-conda-envs/IOOS/lib/python3.6/site-packages/distributed/protocol/core.py", line 96, in loads
    msg = loads_msgpack(small_header, small_payload)
  File "/home/jovyan/my-conda-envs/IOOS/lib/python3.6/site-packages/distributed/protocol/core.py", line 171, in loads_msgpack
    " installed" % str(header['compression']))
ValueError: Data is compressed as lz4 but we don't have this installed
```

Is this a package issue?

I'm running this in a custom `IOOS` environment:
```
jovyan@jupyter-rsignell-2dusgs:~$ source activate IOOS
(IOOS) jovyan@jupyter-rsignell-2dusgs:~$ conda list

# packages in environment at /home/jovyan/my-conda-envs/IOOS:
#
affine                    2.1.0                      py_1    conda-forge
alabaster                 0.7.10                   py36_1    conda-forge
altair                    1.2.1                      py_0    conda-forge
arrow                     0.12.0                   py36_0    conda-forge

affine                    2.1.0                      py_1    conda-forge
alabaster                 0.7.10                   py36_1    conda-forge
altair                    1.2.1                      py_0    conda-forge
arrow                     0.12.0                   py36_0    conda-forge
asciitree                 0.3.3                    py36_1    conda-forge
asn1crypto                0.22.0                   py36_0    conda-forge
astroid                   1.5.3                    py36_0    conda-forge
attrs                     17.4.0                     py_0    conda-forge
babel                     2.5.1                    py36_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.4                      py36_1    conda-forge
bagit                     1.5.5                    py36_1    conda-forge
beautifulsoup4            4.6.0                    py36_0    conda-forge
biggus                    0.15.0                   py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    2.0.0                    py36_0    conda-forge
blinker                   1.4                        py_0    conda-forge
bokeh                     0.12.13                  py36_0    conda-forge
boost                     1.66.0                   py36_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
boto3                     1.5.14                   py36_0    conda-forge
botocore                  1.5.92                   py36_0    conda-forge
bottleneck                1.2.1                    py36_1    conda-forge
branca                    0.2.0                      py_1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.11.5                     0    conda-forge
cachetools                2.0.1                      py_0    conda-forge
cairo                     1.14.10                       0    conda-forge
cartopy                   0.15.1                   py36_5    conda-forge
cc-plugin-glider          1.0.4                    py36_0    conda-forge
cc-plugin-ncei            2.0.2                    py36_0    conda-forge
certifi                   2017.11.5                py36_0    conda-forge
cf_units                  1.2.0                    py36_0    conda-forge
cffi                      1.11.2                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     6.7                        py_1    conda-forge
click-plugins             1.0.3                    py36_0    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
cloudpickle               0.5.2                      py_0    conda-forge
colorama                  0.3.9                    py36_0    conda-forge
compliance-checker        3.1.1                    py36_0    conda-forge
configobj                 5.0.6                    py36_0    defaults
cryptography              2.1.4                    py36_0    conda-forge
ctd                       0.3.0                    py36_0    conda-forge
curl                      7.55.1                        0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cython                    0.27.3                   py36_0    conda-forge
cytoolz                   0.9.0.1                  py36_0    conda-forge
dask                      0.17.1                     py_2    conda-forge
dask-core                 0.17.1                     py_0    conda-forge
dask-kubernetes           0.2.0                     <pip>
dbus                      1.10.22                       0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
descartes                 1.1.0                    py36_0    conda-forge
distributed               1.21.3                   py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
esmf                      7.0.0                         9    conda-forge
expat                     2.2.5                         0    conda-forge
fastcache                 1.0.2                    py36_0    conda-forge
fasteners                 0.14.1                   py36_2    conda-forge
fiona                     1.7.11                   py36_3    conda-forge
flake8                    3.5.0                    py36_0    conda-forge
folium                    0.5.0                      py_0    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
freexl                    1.0.4                         0    conda-forge
gcsfs                     0.0.5                      py_0    conda-forge
gdal                      2.2.3                    py36_0    conda-forge
geojson                   2.3.0                      py_0    conda-forge
geojsonio                 0.0.3                      py_0    conda-forge
geolinks                  0.2.0                    py36_0    conda-forge
geopandas                 0.3.0                    py36_0    conda-forge
geos                      3.6.2                         1    conda-forge
geotiff                   1.4.2                         1    conda-forge
gettext                   0.19.7                        1    conda-forge
giflib                    5.1.4                         0    conda-forge
gitdb2                    2.0.2                    py36_0    conda-forge
github3.py                1.0.0a4                  py36_0    conda-forge
gitpython                 2.1.7                    py36_0    conda-forge
glib                      2.55.0                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
gmpy2                     2.0.8                    py36_1    conda-forge
google-auth               1.4.1                      py_0    conda-forge
google-auth-oauthlib      0.1.0                    py36_0    conda-forge
graphite2                 1.3.10                        0    conda-forge
gridgeo                   0.2.1                    py36_0    conda-forge
gsl                       2.2.1           blas_openblas_4  [blas_openblas]  conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
gsw                       3.2.0                    py36_0    conda-forge
h5netcdf                  0.5.0                      py_0    conda-forge
h5py                      2.7.1                    py36_2    conda-forge
harfbuzz                  1.7.1                         0    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        1    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                          0    conda-forge
idna                      2.6                      py36_1    conda-forge
imagesize                 0.7.1                    py36_0    conda-forge
ioos_tools                1.1.1                      py_0    conda-forge
ipaddress                 1.0.19                    <pip>
ipykernel                 4.7.0                    py36_0    conda-forge
ipython                   6.2.1                    py36_1    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.1.2                    py36_0    conda-forge
iris                      1.13.0                   py36_1    conda-forge
isodate                   0.5.4                    py36_0    conda-forge
isort                     4.2.15                   py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jmespath                  0.9.3                    py36_0    conda-forge
jpeg                      9b                            2    conda-forge
jsanimation               0.1                      py36_0    conda-forge
json-c                    0.12.1                        0    conda-forge
jsonschema                2.6.0                    py36_0    conda-forge
jupyter_client            5.2.1                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kealib                    1.4.7                         4    conda-forge
krb5                      1.14.2                        0    conda-forge
kubernetes                4.0.0                     <pip>
lazy-object-proxy         1.3.1                    py36_0    conda-forge
libboost                  1.65.1               habcd387_4    defaults
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libgdal                   2.2.3                         3    conda-forge
libgfortran               3.0.0                         1    defaults
libiconv                  1.15                          0    conda-forge
libkml                    1.3.0                h8777076_2    defaults
libmo_unpack              3.0                           1    conda-forge
libnetcdf                 4.4.1.1                      10    conda-forge
libpng                    1.6.34                        0    conda-forge
libpq                     9.6.3                         0    conda-forge
libsodium                 1.0.15                        1    conda-forge
libspatialindex           1.8.5                         1    conda-forge
libspatialite             4.3.0a                       19    conda-forge
libssh2                   1.8.0                         2    conda-forge
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
libtiff                   4.0.9                         0    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.7                         0    conda-forge
libxslt                   1.1.32                        0    conda-forge
locket                    0.2.0                    py36_1    conda-forge
lxml                      4.1.1                    py36_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.1.2                    py36_0    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
metakernel                0.20.12                    py_0    conda-forge
mistune                   0.8.3                      py_0    conda-forge
mo_pack                   0.2.0                    py36_1    conda-forge
monotonic                 1.4                      py36_0    conda-forge
mpc                       1.0.3                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
mpich                     3.2                           5    conda-forge
mpmath                    1.0.0                      py_0    conda-forge
msgpack-python            0.4.8                    py36_0    conda-forge
munch                     2.2.0                    py36_0    conda-forge
nb_conda_kernels          2.1.0                    py36_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbdime                    0.4.0                    py36_0    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
nc_time_axis              1.0.2                    py36_0    conda-forge
nco                       4.7.2                         0    conda-forge
ncurses                   5.9                          10    conda-forge
netcdf-fortran            4.4.4                         6    conda-forge
netcdf4                   1.3.1                    py36_1    conda-forge
notebook                  5.2.2                    py36_1    conda-forge
numcodecs                 0.5.4                    py36_0    conda-forge
numexpr                   2.6.4                    py36_0    conda-forge
numpy                     1.14.0          py36_blas_openblas_200  [blas_openblas]  conda-forge
numpydoc                  0.7.0                    py36_0    conda-forge
oauthlib                  2.0.6                      py_0    conda-forge
oceans                    0.4.0                    py36_0    conda-forge
oct2py                    4.0.6                    py36_0    conda-forge
octave_kernel             0.28.3                   py36_0    conda-forge
olefile                   0.44                     py36_0    conda-forge
openblas                  0.2.20                        7    conda-forge
openjpeg                  2.3.0                         2    conda-forge
openssl                   1.0.2n                        0    conda-forge
owslib                    0.16.0                     py_0    conda-forge
paegan                    1.1.4                    py36_0    conda-forge
palettable                3.1.0                      py_0    conda-forge
pandas                    0.22.0                   py36_0    conda-forge
pandoc                    2.1                           0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
pango                     1.40.14                       0    conda-forge
partd                     0.3.8                    py36_0    conda-forge
patsy                     0.5.0                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
pendulum                  1.3.2                    py36_0    conda-forge
pexpect                   4.3.1                    py36_0    conda-forge
phantomjs                 2.1.1                         0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    5.0.0                    py36_0    conda-forge
pip                       9.0.1                    py36_1    conda-forge
pixman                    0.34.0                        1    conda-forge
pluggy                    0.6.0                      py_0    conda-forge
pocean-core               1.3.0                      py_0    conda-forge
poppler                   0.61.1                        3    conda-forge
poppler-data              0.4.8                         0    conda-forge
proj4                     4.9.3                         5    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
protobuf                  3.5.1                    py36_3    conda-forge
psutil                    5.4.0                    py36_0    conda-forge
psycopg2                  2.7.3.2                  py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py                        1.5.2                      py_0    conda-forge
pyasn1                    0.4.2                      py_0    conda-forge
pyasn1-modules            0.2.1                      py_0    conda-forge
pycodestyle               2.3.1                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pyepsg                    0.3.2                    py36_0    conda-forge
pyflakes                  1.6.0                    py36_0    conda-forge
pygc                      1.2.1                    py36_0    conda-forge
pygeoif                   0.7                      py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyjwt                     1.5.3                      py_0    conda-forge
pykdtree                  1.2.2                    py36_1    conda-forge
pyke                      1.1.1                    py36_0    conda-forge
pylint                    1.8.1                    py36_0    conda-forge
pyoos                     0.8.4                    py36_0    conda-forge
pyopenssl                 17.4.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pyresample                1.7.1                    py36_0    conda-forge
pysal                     1.14.3                   py36_0    conda-forge
pysgrid                   0.3.5                    py36_0    conda-forge
pyshp                     1.2.12                     py_0    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
pytest                    3.3.2                    py36_0    conda-forge
python                    3.6.4                         0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.3                     py_2    conda-forge
pytzdata                  2017.3.1                   py_0    conda-forge
pyugrid                   0.3.1                    py36_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     16.0.2                   py36_0    defaults
qt                        5.6.2                         7    conda-forge
qtawesome                 0.4.4                    py36_0    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
qtpy                      1.3.1                    py36_0    conda-forge
r-assertthat              0.1                    r3.4.1_0    conda-forge
r-backports               1.0.5                  r3.4.1_0    conda-forge
r-base                    3.4.1                         3    conda-forge
r-base64enc               0.1_3                  r3.4.1_0    conda-forge
r-bh                      1.65.0_1               r3.4.1_0    conda-forge
r-bindr                   0.1                    r3.4.1_0    conda-forge
r-bindrcpp                0.2                    r3.4.1_0    conda-forge
r-bitops                  1.0_6                  r3.4.1_0    conda-forge
r-brew                    1.0_6                  r3.4.1_0    conda-forge
r-catools                 1.17.1                 r3.4.1_0    conda-forge
r-cluster                 2.0.6                  r3.4.1_0    conda-forge
r-codetools               0.2_15                 r3.4.1_0    conda-forge
r-colorspace              1.3_2                  r3.4.1_0    conda-forge
r-crayon                  1.3.2                  r3.4.1_0    conda-forge
r-crosstalk               1.0.0                  r3.4.1_0    conda-forge
r-crul                    0.5.0                  r3.4.1_0    conda-forge
r-curl                    3.1                    r3.4.1_0    conda-forge
r-data.table              1.10.4                 r3.4.1_0    conda-forge
r-data.tree               0.7.4                  r3.4.1_0    conda-forge
r-dbi                     0.6_1                  r3.4.1_0    conda-forge
r-diagrammer              0.9.2                  r3.4.1_0    conda-forge
r-dichromat               2.0_0                  r3.4.1_0    conda-forge
r-digest                  0.6.12                 r3.4.1_0    conda-forge
r-doparallel              1.0.10                 r3.4.1_0    conda-forge
r-downloader              0.4                    r3.4.1_0    conda-forge
r-dplyr                   0.7.4                  r3.4.1_0    conda-forge
r-dt                      0.2                    r3.4.1_0    conda-forge
r-eml                     1.0.3                  r3.4.1_0    conda-forge
r-evaluate                0.10.1                 r3.4.1_0    conda-forge
r-finch                   0.1.0                  r3.4.1_0    conda-forge
r-foreach                 1.4.3                  r3.4.1_0    conda-forge
r-geosphere               1.5_5                  r3.4.1_0    conda-forge
r-ggfortify               0.4.1                  r3.4.1_0    conda-forge
r-ggplot2                 2.2.1                  r3.4.1_0    conda-forge
r-glue                    1.1.1                  r3.4.1_0    conda-forge
r-gridbase                0.4_7                  r3.4.1_0    conda-forge
r-gridextra               2.3                    r3.4.1_0    conda-forge
r-gsw                     1.0_3                  r3.4.1_0    conda-forge
r-gtable                  0.2.0                  r3.4.1_0    conda-forge
r-highr                   0.6                    r3.4.1_0    conda-forge
r-hms                     0.3                    r3.4.1_0    conda-forge
r-hoardr                  0.2.0                  r3.4.1_0    conda-forge
r-htmltools               0.3.6                  r3.4.1_0    conda-forge
r-htmlwidgets             0.9                    r3.4.1_0    conda-forge
r-httpcode                0.2.0                  r3.4.1_0    conda-forge
r-httpuv                  1.3.5                  r3.4.1_0    conda-forge
r-httr                    1.2.1                  r3.4.1_0    conda-forge
r-igraph                  1.1.2                  r3.4.1_0    conda-forge
r-influencer              0.1.0                  r3.4.1_0    conda-forge
r-irdisplay               0.4.4                  r3.4.1_0    conda-forge
r-irkernel                0.8.11                 r3.4.1_0    conda-forge
r-irlba                   2.1.2                  r3.4.1_0    conda-forge
r-iterators               1.0.8                  r3.4.1_0    conda-forge
r-jsonlite                1.4                    r3.4.1_0    conda-forge
r-knitr                   1.16                   r3.4.1_0    conda-forge
r-labeling                0.3                    r3.4.1_0    conda-forge
r-lattice                 0.20_34                r3.4.1_0    conda-forge
r-lazyeval                0.2.0                  r3.4.1_0    conda-forge
r-leaflet                 1.1.0                  r3.4.1_0    conda-forge
r-lubridate               1.6.0                  r3.4.1_0    conda-forge
r-magrittr                1.5                    r3.4.1_0    conda-forge
r-mapdata                 2.2_6                  r3.4.1_0    conda-forge
r-maps                    3.2.0                  r3.4.1_0    conda-forge
r-markdown                0.8                    r3.4.1_1    conda-forge
r-mass                    7.3_45                 r3.4.1_0    conda-forge
r-matrix                  1.2_7.1                r3.4.1_0    conda-forge
r-mime                    0.5                    r3.4.1_0    conda-forge
r-munsell                 0.4.3                  r3.4.1_0    conda-forge
r-ncdf4                   1.16                   r3.4.1_1    conda-forge
r-nmf                     0.20.6                 r3.4.1_0    conda-forge
r-obistools               0.0.5                  r3.4.1_0    conda-forge
r-oce                     0.9_20                 r3.4.1_0    conda-forge
r-openssl                 0.9.7                  r3.4.1_0    conda-forge
r-pbdzmq                  0.3_1                  r3.4.1_0    conda-forge
r-pkgconfig               2.0.1                  r3.4.1_0    conda-forge
r-pkgmaker                0.22                   r3.4.1_0    conda-forge
r-plogr                   0.1_1                  r3.4.1_0    conda-forge
r-plyr                    1.8.4                  r3.4.1_0    conda-forge
r-png                     0.1_7                  r3.4.1_0    conda-forge
r-purrr                   0.2.3                  r3.4.1_0    conda-forge
r-r6                      2.2.0                  r3.4.1_0    conda-forge
r-rappdirs                0.3.1                  r3.4.1_0    conda-forge
r-raster                  2.6_7                  r3.4.1_0    conda-forge
r-rcolorbrewer            1.1_2                  r3.4.1_0    conda-forge
r-rcpp                    0.12.13                r3.4.1_0    conda-forge
r-readr                   1.1.1                  r3.4.1_0    conda-forge
r-registry                0.3                    r3.4.1_0    conda-forge
r-repr                    0.10                   r3.4.1_0    conda-forge
r-rerddap                 0.4.2                  r3.4.1_0    conda-forge
r-reshape2                1.4.2                  r3.4.1_0    conda-forge
r-rgdal                   1.2_16                 r3.4.1_0    conda-forge
r-rgeos                   0.3_26                 r3.4.1_0    conda-forge
r-rgexf                   0.15.3                 r3.4.1_0    conda-forge
r-rlang                   0.1.2                  r3.4.1_0    conda-forge
r-rmarkdown               1.6                    r3.4.1_2    conda-forge
r-rngtools                1.2.4                  r3.4.1_0    conda-forge
r-robis                   1.0.0                  r3.4.1_0    conda-forge
r-rook                    1.1_1                  r3.4.1_0    conda-forge
r-rprojroot               1.2                    r3.4.1_0    conda-forge
r-rstudioapi              0.7                    r3.4.1_0    conda-forge
r-scales                  0.5.0                  r3.4.1_0    conda-forge
r-sf                      0.4_1                  r3.4.1_0    conda-forge
r-shiny                   1.0.5                  r3.4.1_0    conda-forge
r-sourcetools             0.1.6                  r3.4.1_0    conda-forge
r-sp                      1.2_4                  r3.4.1_0    conda-forge
r-stringi                 1.1.2                  r3.4.1_0    conda-forge
r-stringr                 1.2.0                  r3.4.1_0    conda-forge
r-tibble                  1.3.3                  r3.4.1_0    conda-forge
r-tidyr                   0.7.1                  r3.4.1_0    conda-forge
r-tidyselect              0.2.3                  r3.4.1_0    conda-forge
r-triebeard               0.3.0                  r3.4.1_0    conda-forge
r-udunits2                0.13                   r3.4.1_0    conda-forge
r-units                   0.5_1                  r3.4.1_0    conda-forge
r-urltools                1.7.0                  r3.4.1_0    conda-forge
r-uuid                    0.1_2                  r3.4.1_0    conda-forge
r-viridis                 0.4.0                  r3.4.1_0    conda-forge
r-viridislite             0.2.0                  r3.4.1_0    conda-forge
r-visnetwork              2.0.3                  r3.4.1_0    conda-forge
r-worrms                  0.2.0                  r3.4.1_0    conda-forge
r-xml                     3.98_1.6               r3.4.1_0    conda-forge
r-xml2                    1.1.1                  r3.4.1_0    conda-forge
r-xtable                  1.8_2                  r3.4.1_0    conda-forge
r-xtractomatic            3.3.2                  r3.4.1_0    conda-forge
r-xts                     0.9_7                  r3.4.1_0    conda-forge
r-yaml                    2.1.14                 r3.4.1_0    conda-forge
r-zoo                     1.7_14                 r3.4.1_0    conda-forge
rasterio                  0.36.0                   py36_3    conda-forge
readline                  7.0                           0    conda-forge
regex                     2017.07.28               py36_0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
requests-oauthlib         0.8.0                    py36_1    conda-forge
retrying                  1.3.3                    py36_1    conda-forge
rope                      0.10.7                   py36_0    conda-forge
rpy2                      2.8.5              py36r3.4.1_0    conda-forge
rsa                       3.4.2                    py36_0    conda-forge
rtree                     0.8.3                    py36_0    conda-forge
s3transfer                0.1.11                   py36_0    conda-forge
scikit-learn              0.19.1          py36_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.0.0           py36_blas_openblas_201  [blas_openblas]  conda-forge
seaborn                   0.8.1                    py36_0    conda-forge
seawater                  3.3.4                    py36_0    conda-forge
selenium                  3.8.1                    py36_0    conda-forge
sensorml2iso              1.0.2                    py36_1    conda-forge
setuptools                38.4.0                   py36_0    conda-forge
shapely                   1.6.3                    py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
simplejson                3.11.1                   py36_0    conda-forge
singledispatch            3.4.0.3                  py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
siphon                    0.6.1                    py36_0    conda-forge
six                       1.10.0                   py36_1    conda-forge
smmap2                    2.0.3                    py36_0    conda-forge
snowballstemmer           1.2.1                    py36_0    conda-forge
snuggs                    1.4.1                    py36_0    conda-forge
sortedcontainers          1.5.7                    py36_0    conda-forge
sphinx                    1.6.6                    py36_0    conda-forge
sphinxcontrib-websupport  1.0.1                    py36_0    conda-forge
spyder                    3.2.6                    py36_0    conda-forge
sqlalchemy                1.1.13                   py36_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
statsmodels               0.8.0                    py36_0    conda-forge
sympy                     1.1.1                    py36_0    conda-forge
tblib                     1.3.2                    py36_0    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
thredds_crawler           1.5.3                    py36_0    conda-forge
timeout-decorator         0.4.0                      py_0    conda-forge
tk                        8.6.7                         0    conda-forge
toolz                     0.8.2                      py_2    conda-forge
tornado                   4.5.3                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
typing                    3.6.2                    py36_0    conda-forge
tzlocal                   1.5.1                      py_0    conda-forge
udunits2                  2.2.25                        1    conda-forge
uritemplate.py            3.0.2                    py36_0    conda-forge
urllib3                   1.22                     py36_0    conda-forge
utide                     0.2.1                      py_0    conda-forge
util-linux                2.21                          0    defaults
vega                      0.4.4                    py36_1    conda-forge
vincent                   0.4.4                    py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
websocket-client          0.40.0                    <pip>
wheel                     0.30.0                   py36_2    conda-forge
widgetsnbextension        3.1.4                    py36_0    conda-forge
windrose                  1.6.3                      py_0    conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
xarray                    0.10.2                   py36_0    conda-forge
xerces-c                  3.2.0                         0    conda-forge
xlrd                      1.1.0                      py_2    conda-forge
xorg-kbproto              1.0.7                         1    conda-forge
xorg-libx11               1.6.4                         6    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xorg-libxrender           0.9.10                        0    conda-forge
xorg-renderproto          0.11.1                        1    conda-forge
xorg-xproto               7.0.31                        6    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zarr                      2.2.0                      py_1    conda-forge
zeromq                    4.1.5                         0    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by mrocklin** [comment]
Both the client and worker environments will need to agree on if they have
lz4 or not.  You might try calling client.get_versions(check=True)

**Comment by rsignell-usgs** [comment]
Indeed, `client.get_versions(check=True)` displayed some mismatched versions:
```
ValueError: Mismatched versions found

blosc
+-------------------------+---------+
|                         | version |
+-------------------------+---------+
| client                  | None    |
| tcp://10.22.34.13:43910 | 1.4.4   |
+-------------------------+---------+

bokeh
+-------------------------+---------+
|                         | version |
+-------------------------+---------+
| client                  | 0.12.13 |
| tcp://10.22.34.13:43910 | 0.12.14 |
+-------------------------+---------+

lz4
+-------------------------+---------+
|                         | version |
+-------------------------+---------+
| client                  | None    |
| tcp://10.22.34.13:43910 | 0.10.1  |
+-------------------------+---------+

msgpack
+-------------------------+---------+
|                         | version |
+-------------------------+---------+
| client                  | 0.4.8   |
| tcp://10.22.34.13:43910 | 0.5.5   |
+-------------------------+---------+

numpy
+-------------------------+---------+
|                         | version |
+-------------------------+---------+
| client                  | 1.14.0  |
| tcp://10.22.34.13:43910 | 1.14.1  |
+-------------------------+---------+

toolz
+-------------------------+---------+
|                         | version |
+-------------------------+---------+
| client                  | 0.8.2   |
| tcp://10.22.34.13:43910 | 0.9.0   |
+-------------------------+---------+
```
and in particular, `blosc` was missing, so  a simple `conda install blosc` fixed the problem!

This is a super useful tool!  Thanks @mrocklin !

**Comment by mrocklin** [comment]
I didn't make it, but I'm glad you like it :)
