### ISSUE TITLE
decrease warning / error verbosity with adaptive scheduler

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#165]
I am playing around with `dask_kubernetes.KubeCluster` and its adaptive capabilities. I have to say that this is a fantastic feature! I love watching the cluster scale up to handle big computations.

But I am getting lots of noise in terms of errors and warnings. For example
```
distributed.scheduler - ERROR - Failed to connect to worker 'tcp://10.20.237.27:33762': Timed out trying to connect to 'tcp://10.20.237.27:33762' after 3.0 s: in <distributed.comm.tcp.TCPConnector object at 0x7f7bd5196278>: ConnectionRefusedError: [Errno 111] Connection refused
distributed.scheduler - ERROR - Failed to connect to worker 'tcp://10.20.236.24:38907': Timed out trying to connect to 'tcp://10.20.236.24:38907' after 3.0 s: in <distributed.comm.tcp.TCPConnector object at 0x7f7bd50c8128>: ConnectionRefusedError: [Errno 111] Connection refused
distributed.scheduler - ERROR - Failed to connect to worker 'tcp://10.20.246.24:40042': Timed out trying to connect to 'tcp://10.20.246.24:40042' after 3.0 s: connect() didn't finish in time
distributed.scheduler - ERROR - Failed to connect to worker 'tcp://10.20.239.25:42550': Timed out trying to connect to 'tcp://10.20.239.25:42550' after 3.0 s: connect() didn't finish in time
...
```

These don't seem to be fatal. The calculations work. So this is just noise on my notebook.

**Comment by mrocklin** [comment]
Might be worse than that.  These workers are still alive.  Killing them now manually.

```python
mrocklin@carbon:~$ kubectl get pods -n pangeo
NAME                            READY     STATUS    RESTARTS   AGE
dask-rabernat-6b582c66-d2fc6j   1/1       Running   0          22h
dask-rabernat-6b582c66-d5l2lc   1/1       Running   0          22h
dask-rabernat-6b582c66-d6czgz   1/1       Running   0          22h
dask-rabernat-6b582c66-d7bj4h   1/1       Running   0          22h
dask-rabernat-6b582c66-d8sbbq   1/1       Running   0          22h
dask-rabernat-6b582c66-dc5r7p   1/1       Running   0          22h
dask-rabernat-6b582c66-dd4xrb   1/1       Running   0          22h
dask-rabernat-6b582c66-dfn5gp   1/1       Running   0          22h
dask-rabernat-6b582c66-dg45sl   1/1       Running   0          22h
dask-rabernat-6b582c66-dgb9cg   1/1       Running   0          22h
dask-rabernat-6b582c66-dhzxmr   1/1       Running   0          22h
dask-rabernat-6b582c66-dkd9rb   1/1       Running   0          22h
dask-rabernat-6b582c66-dmghtb   1/1       Running   0          22h
dask-rabernat-6b582c66-dnp28c   1/1       Running   0          22h
dask-rabernat-6b582c66-dpf5s5   1/1       Running   0          22h
dask-rabernat-6b582c66-dpphkm   1/1       Running   0          22h
dask-rabernat-6b582c66-dqwn9n   1/1       Running   0          22h
dask-rabernat-6b582c66-drlml9   1/1       Running   0          22h
dask-rabernat-6b582c66-dshlmc   1/1       Running   0          22h
dask-rabernat-6b582c66-dt2m4d   1/1       Running   0          22h
dask-rabernat-6b582c66-dth4m9   1/1       Running   0          22h
dask-rabernat-6b582c66-dvdx9w   1/1       Running   0          22h
dask-rabernat-6b582c66-dvlh8h   1/1       Running   0          22h
hub-5fc6b6f9f6-8jsbx            1/1       Running   0          5h
jupyter-rsignell-2dusgs         1/1       Running   0          19h
proxy-584cf885d7-wd5pn          2/2       Running   0          5h
```

<details>

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 241, in heartbeat
    **self.monitor.recent())
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 474, in send_recv_from_rpc
    comm = yield self.live_comm()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 450, in live_comm
    connection_args=self.connection_args)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/core.py", line 196, in connect
    _raise(error)
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/core.py", line 179, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://10.20.221.4:39512' after 3.0 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7ff3824ff268>, <tornado.concurrent.Future object at 0x7ff3826ab908>)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/core.py", line 187, in connect
    quiet_exceptions=EnvironmentError)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
tornado.gen.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 241, in heartbeat
    **self.monitor.recent())
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 474, in send_recv_from_rpc
    comm = yield self.live_comm()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 450, in live_comm
    connection_args=self.connection_args)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/core.py", line 196, in connect
    _raise(error)
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/core.py", line 179, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://10.20.221.4:39512' after 3.0 s: connect() didn't finish in time
```

</details>
