### ISSUE TITLE
Writing to FUSE mount for workers

### ISSUE THREAD

**Issue by kaipak** [pangeo-data/pangeo#215]
I create some random data and a Zarr array on local disk. Running this without KubeCluster works just fine.

```
dask_arr  = da.random.normal(10, 0.1, size=(100, 1000, 1000), chunks=chunks)
zloc  = zarr.create(shape=dask_arr.shape, chunks=chunks, 
                   dtype=dask_arr.dtype, store='/home/jovyan/foo', 
                   overwrite=True)
dask_arr.store(zloc, lock=False)
```
A couple issues. When I try to write to local disk, I get failures which I think is related to the permission problems we were seeing with gcsfs in #209 so that's expected. 

However, when I do this with KubeCluster on a FUSE mount, it fails with a different issue:

```
zfuse = zarr.create(shape=dask_arr.shape, chunks=chunks, 
                                dtype=dask_arr.dtype, store='/gcs/storage-benchmarks/foo', 
                                overwrite=True)
dask_arr.store(zfuse, lock=False)
```

```
distributed.scheduler - ERROR - error from worker tcp://10.20.52.7:38349: [Errno 14] Bad address: '/gcs/storage-benchmarks/foo/2.0.0.nr6wp1bu.partial'
distributed.utils - ERROR - [Errno 14] Bad address: '/gcs/storage-benchmarks/foo/2.0.0.nr6wp1bu.partial'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/utils.py", line 238, in f
    result[0] = yield make_coro()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/client.py", line 1378, in _gather
    traceback)
  File "/opt/conda/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.6/site-packages/dask/array/core.py", line 2693, in store_chunk
    return load_store_chunk(x, out, index, lock, return_stored, False)
  File "/opt/conda/lib/python3.6/site-packages/dask/array/core.py", line 2682, in load_store_chunk
    out[index] = np.asanyarray(x)
  File "/opt/conda/lib/python3.6/site-packages/zarr/core.py", line 1102, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/opt/conda/lib/python3.6/site-packages/zarr/core.py", line 1197, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/opt/conda/lib/python3.6/site-packages/zarr/core.py", line 1488, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/opt/conda/lib/python3.6/site-packages/zarr/core.py", line 1536, in _set_selection
    self._chunk_setitem(chunk_coords, chunk_selection, chunk_value, fields=fields)
  File "/opt/conda/lib/python3.6/site-packages/zarr/core.py", line 1644, in _chunk_setitem
    fields=fields)
  File "/opt/conda/lib/python3.6/site-packages/zarr/core.py", line 1721, in _chunk_setitem_nosync
    self.chunk_store[ckey] = cdata
  File "/opt/conda/lib/python3.6/site-packages/zarr/storage.py", line 768, in __setitem__
    suffix='.partial') as f:
  File "/opt/conda/lib/python3.6/tempfile.py", line 549, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/opt/conda/lib/python3.6/tempfile.py", line 260, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 14] Bad address: '/gcs/storage-benchmarks/foo/2.0.0.nr6wp1bu.partial'

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-25-04f6ad3e103e> in <module>()
----> 1 dask_arr.store(zloc, lock=False)

/opt/conda/lib/python3.6/site-packages/dask/array/core.py in store(self, target, **kwargs)
   1209     @wraps(store)
   1210     def store(self, target, **kwargs):
-> 1211         r = store([self], [target], **kwargs)
   1212 
   1213         if kwargs.get("return_stored", False):

/opt/conda/lib/python3.6/site-packages/dask/array/core.py in store(sources, targets, lock, regions, compute, return_stored, **kwargs)
    953 
    954         if compute:
--> 955             result.compute(**kwargs)
    956             return None
    957         else:

/opt/conda/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    153         dask.base.compute
    154         """
--> 155         (result,) = compute(self, traverse=False, **kwargs)
    156         return result
    157 

/opt/conda/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    402     postcomputes = [a.__dask_postcompute__() if is_dask_collection(a)
    403                     else (None, a) for a in args]
--> 404     results = get(dsk, keys, **kwargs)
    405     results_iter = iter(results)
    406     return tuple(a if f is None else f(next(results_iter), *a)

/opt/conda/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, **kwargs)
   2073             try:
   2074                 results = self.gather(packed, asynchronous=asynchronous,
-> 2075                                       direct=direct)
   2076             finally:
   2077                 for f in futures.values():

/opt/conda/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, maxsize, direct, asynchronous)
   1498             return self.sync(self._gather, futures, errors=errors,
   1499                              direct=direct, local_worker=local_worker,
-> 1500                              asynchronous=asynchronous)
   1501 
   1502     @gen.coroutine

/opt/conda/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    613             return future
    614         else:
--> 615             return sync(self.loop, func, *args, **kwargs)
    616 
    617     def __repr__(self):

/opt/conda/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    252             e.wait(10)
    253     if error[0]:
--> 254         six.reraise(*error[0])
    255     else:
    256         return result[0]

/opt/conda/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/opt/conda/lib/python3.6/site-packages/distributed/utils.py in f()
    236             yield gen.moment
    237             thread_state.asynchronous = True
--> 238             result[0] = yield make_coro()
    239         except Exception as exc:
    240             logger.exception(exc)

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/opt/conda/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1376                             six.reraise(type(exception),
   1377                                         exception,
-> 1378                                         traceback)
   1379                     if errors == 'skip':
   1380                         bad_keys.add(key)

/opt/conda/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

/opt/conda/lib/python3.6/site-packages/dask/array/core.py in store_chunk()
   2691 
   2692 def store_chunk(x, out, index, lock, return_stored):
-> 2693     return load_store_chunk(x, out, index, lock, return_stored, False)
   2694 
   2695 

/opt/conda/lib/python3.6/site-packages/dask/array/core.py in load_store_chunk()
   2680     try:
   2681         if x is not None:
-> 2682             out[index] = np.asanyarray(x)
   2683         if return_stored and load_stored:
   2684             result = out[index]

/opt/conda/lib/python3.6/site-packages/zarr/core.py in __setitem__()
   1100 
   1101         fields, selection = pop_fields(selection)
-> 1102         self.set_basic_selection(selection, value, fields=fields)
   1103 
   1104     def set_basic_selection(self, selection, value, fields=None):

/opt/conda/lib/python3.6/site-packages/zarr/core.py in set_basic_selection()
   1195             return self._set_basic_selection_zd(selection, value, fields=fields)
   1196         else:
-> 1197             return self._set_basic_selection_nd(selection, value, fields=fields)
   1198 
   1199     def set_orthogonal_selection(self, selection, value, fields=None):

/opt/conda/lib/python3.6/site-packages/zarr/core.py in _set_basic_selection_nd()
   1486         indexer = BasicIndexer(selection, self)
   1487 
-> 1488         self._set_selection(indexer, value, fields=fields)
   1489 
   1490     def _set_selection(self, indexer, value, fields=None):

/opt/conda/lib/python3.6/site-packages/zarr/core.py in _set_selection()
   1534 
   1535             # put data
-> 1536             self._chunk_setitem(chunk_coords, chunk_selection, chunk_value, fields=fields)
   1537 
   1538     def _chunk_getitem(self, chunk_coords, chunk_selection, out, out_selection,

/opt/conda/lib/python3.6/site-packages/zarr/core.py in _chunk_setitem()
   1642         with lock:
   1643             self._chunk_setitem_nosync(chunk_coords, chunk_selection, value,
-> 1644                                        fields=fields)
   1645 
   1646     def _chunk_setitem_nosync(self, chunk_coords, chunk_selection, value, fields=None):

/opt/conda/lib/python3.6/site-packages/zarr/core.py in _chunk_setitem_nosync()
   1719 
   1720         # store
-> 1721         self.chunk_store[ckey] = cdata
   1722 
   1723     def _chunk_key(self, chunk_coords):

/opt/conda/lib/python3.6/site-packages/zarr/storage.py in __setitem__()
    766             with tempfile.NamedTemporaryFile(mode='wb', delete=False, dir=dir_path,
    767                                              prefix=file_name + '.',
--> 768                                              suffix='.partial') as f:
    769                 temp_path = f.name
    770                 f.write(value)

/opt/conda/lib/python3.6/tempfile.py in NamedTemporaryFile()
    547         flags |= _os.O_TEMPORARY
    548 
--> 549     (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
    550     try:
    551         file = _io.open(fd, mode, buffering=buffering,

/opt/conda/lib/python3.6/tempfile.py in _mkstemp_inner()
    258         file = _os.path.join(dir, pre + name + suf)
    259         try:
--> 260             fd = _os.open(file, flags, 0o600)
    261         except FileExistsError:
    262             continue    # try again

OSError: [Errno 14] Bad address: '/gcs/storage-benchmarks/foo/2.0.0.nr6wp1bu.partial'

distributed.scheduler - ERROR - error from worker tcp://10.20.8.13:35304: [Errno 14] Bad address: '/gcs/storage-benchmarks/foo/7.0.0.vx5kc_m0.partial'
distributed.scheduler - ERROR - error from worker tcp://10.20.13.12:42373: [Errno 14] Bad address: '/gcs/storage-benchmarks/foo/12.0.0.rwqy18gn.partial'
distributed.scheduler - ERROR - error from worker tcp://10.20.8.12:37211: [Errno 14] Bad address: '/gcs/storage-benchmarks/foo/6.0.0.n0356j0e.partial'
distributed.scheduler - ERROR - error from worker tcp://10.20.24.12:44243: [Errno 14] Bad address: '/gcs/storage-benchmarks/foo/17.0.0.23e7rkjl.partial'
distributed.scheduler - ERROR - error from worker tcp://10.20.79.9:33406: [Errno 14] Bad address: '/gcs/storage-benchmarks/foo/5.0.0._h8p7_52.partial'
distributed.scheduler - ERROR - error from worker tcp://10.20.95.7:40622: [Errno 14] Bad address: '/gcs/storage-benchmarks/foo/1.0.0.trx6i37x.partial'
```

Might be related to issue #202. Reading data and running computations from fuse works as expected.

**Comment by jgerardsimcock** [comment]
@kaipak Are you not back in the situation where you need your gcs credentials to be passed to your workers?

**Comment by kaipak** [comment]
> @kaipak Are you not back in the situation where you need your gcs credentials to be passed to your workers?

I suppose so, but I am unsure how to pass tokens to workers in the context of a FUSE mount. Seems like [this script](https://github.com/pangeo-data/pangeo/blob/ca40016fb2b63c6c30a60ec38d24a497550263d8/gce/worker/prepare.sh) is run when the containers are provisioned and it mounts pangeo-data so potentially I could modify worker-template.yaml?

**Comment by tjcrone** [comment]
In my testing of an experimental [zarr GCSStore class,](https://github.com/zarr-developers/zarr/pull/252) I am using the following code to generate an Oauth credentials object that can be passed to workers:
```
import google.auth
credentials, project = google.auth.default()
```
I believe for this to work you would need the Google Cloud SDK, as well as the google-auth package. Authenticating can be a accomplished with
```
gcloud auth application-default login --no-launch-browser
```
I wonder if this could work here as well?

More info [here](https://google-auth.readthedocs.io/en/latest/user-guide.html).
