### ISSUE TITLE
distributed errors on latest pangeo.pydata.org deployment

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#236]
When attempting to access the Workers page of the KubeCluster dashboard, I am getting a "500 server error". In the notebook, I see this error message

```
distributed.utils - ERROR - unexpected attribute 'index_position' to DataTable, possible attributes are columns, css_classes, disabled, editable, fit_columns, height, js_event_callbacks, js_property_callbacks, name, reorderable, row_headers, scroll_to_selection, selectable, sizing_mode, sortable, source, subscribed_events, tags, view or width
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/utils.py", line 622, in log_errors
    yield
  File "/opt/conda/lib/python3.6/site-packages/distributed/bokeh/scheduler.py", line 1082, in workers_doc
    table = WorkerTable(scheduler)
  File "/opt/conda/lib/python3.6/site-packages/distributed/bokeh/scheduler.py", line 963, in __init__
    reorderable=True, sortable=True, width=width, **dt_kwargs
  File "/opt/conda/lib/python3.6/site-packages/bokeh/models/widgets/tables.py", line 493, in __init__
    super(TableWidget, self).__init__(**kw)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/model.py", line 219, in __init__
    super(Model, self).__init__(**kwargs)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/core/has_props.py", line 236, in __init__
    setattr(self, name, value)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/core/has_props.py", line 271, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))
AttributeError: unexpected attribute 'index_position' to DataTable, possible attributes are columns, css_classes, disabled, editable, fit_columns, height, js_event_callbacks, js_property_callbacks, name, reorderable, row_headers, scroll_to_selection, selectable, sizing_mode, sortable, source, subscribed_events, tags, view or width
tornado.application - ERROR - Uncaught exception GET /workers (::1)
HTTPServerRequest(protocol='http', host='pangeo.pydata.org', method='GET', uri='/workers', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/server/views/doc_handler.py", line 21, in get
    session = yield self.get_session()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/server/views/session_handler.py", line 43, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/server/application_context.py", line 182, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/util/api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/application/application.py", line 179, in initialize_document
    h.modify_document(doc)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/util/api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/application/handlers/function.py", line 131, in modify_document
    self._func(doc)
  File "/opt/conda/lib/python3.6/site-packages/distributed/bokeh/scheduler.py", line 1082, in workers_doc
    table = WorkerTable(scheduler)
  File "/opt/conda/lib/python3.6/site-packages/distributed/bokeh/scheduler.py", line 963, in __init__
    reorderable=True, sortable=True, width=width, **dt_kwargs
  File "/opt/conda/lib/python3.6/site-packages/bokeh/models/widgets/tables.py", line 493, in __init__
    super(TableWidget, self).__init__(**kw)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/model.py", line 219, in __init__
    super(Model, self).__init__(**kwargs)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/core/has_props.py", line 236, in __init__
    setattr(self, name, value)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/core/has_props.py", line 271, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))
AttributeError: unexpected attribute 'index_position' to DataTable, possible attributes are columns, css_classes, disabled, editable, fit_columns, height, js_event_callbacks, js_property_callbacks, name, reorderable, row_headers, scroll_to_selection, selectable, sizing_mode, sortable, source, subscribed_events, tags, view or width
distributed.utils - ERROR - unexpected attribute 'index_position' to DataTable, possible attributes are columns, css_classes, disabled, editable, fit_columns, height, js_event_callbacks, js_property_callbacks, name, reorderable, row_headers, scroll_to_selection, selectable, sizing_mode, sortable, source, subscribed_events, tags, view or width
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/utils.py", line 622, in log_errors
    yield
  File "/opt/conda/lib/python3.6/site-packages/distributed/bokeh/scheduler.py", line 1082, in workers_doc
    table = WorkerTable(scheduler)
  File "/opt/conda/lib/python3.6/site-packages/distributed/bokeh/scheduler.py", line 963, in __init__
    reorderable=True, sortable=True, width=width, **dt_kwargs
  File "/opt/conda/lib/python3.6/site-packages/bokeh/models/widgets/tables.py", line 493, in __init__
    super(TableWidget, self).__init__(**kw)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/model.py", line 219, in __init__
    super(Model, self).__init__(**kwargs)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/core/has_props.py", line 236, in __init__
    setattr(self, name, value)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/core/has_props.py", line 271, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))
AttributeError: unexpected attribute 'index_position' to DataTable, possible attributes are columns, css_classes, disabled, editable, fit_columns, height, js_event_callbacks, js_property_callbacks, name, reorderable, row_headers, scroll_to_selection, selectable, sizing_mode, sortable, source, subscribed_events, tags, view or width
tornado.application - ERROR - Uncaught exception GET /workers (::1)
HTTPServerRequest(protocol='http', host='pangeo.pydata.org', method='GET', uri='/workers', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/server/views/doc_handler.py", line 21, in get
    session = yield self.get_session()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/server/views/session_handler.py", line 43, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/server/application_context.py", line 182, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/util/api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/application/application.py", line 179, in initialize_document
    h.modify_document(doc)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/util/api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/application/handlers/function.py", line 131, in modify_document
    self._func(doc)
  File "/opt/conda/lib/python3.6/site-packages/distributed/bokeh/scheduler.py", line 1082, in workers_doc
    table = WorkerTable(scheduler)
  File "/opt/conda/lib/python3.6/site-packages/distributed/bokeh/scheduler.py", line 963, in __init__
    reorderable=True, sortable=True, width=width, **dt_kwargs
  File "/opt/conda/lib/python3.6/site-packages/bokeh/models/widgets/tables.py", line 493, in __init__
    super(TableWidget, self).__init__(**kw)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/model.py", line 219, in __init__
    super(Model, self).__init__(**kwargs)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/core/has_props.py", line 236, in __init__
    setattr(self, name, value)
  File "/opt/conda/lib/python3.6/site-packages/bokeh/core/has_props.py", line 271, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))
AttributeError: unexpected attribute 'index_position' to DataTable, possible attributes are columns, css_classes, disabled, editable, fit_columns, height, js_event_callbacks, js_property_callbacks, name, reorderable, row_headers, scroll_to_selection, selectable, sizing_mode, sortable, source, subscribed_events, tags, view or width
```

This is reminiscent of the error described in #206. 

I verified the notebook is running bokeh version `0.12.15dev3` and distributed version `1.21.6`.

@mrocklin - is this a known issue, or something unique to our setup?

**Comment by mrocklin** [comment]
My first guess is that the version numbers are lying.

**Comment by mrocklin** [comment]
I don't think so, no.  We don't expose those ports from the workers anyway

**Comment by jgerardsimcock** [comment]
@rabernat the distributed versions in the two Dockerfiles in pangeo/gce is 1.21.4. Which images are the current deployments helm chart pulling from?

**Comment by rabernat** [comment]
It appears that this was NOT resolved by upgrading distributed (#239).

**Comment by jhamman** [comment]
@mrocklin - these errors seem to be gone. Okay to close?

**Comment by mrocklin** [comment]
I'm glad to hear it!  No objection to closing from me.
