### ISSUE TITLE
HTTP 500 and HTTP 400 Errors on pangeo.pydata.org

### ISSUE THREAD

**Issue by willirath** [pangeo-data/pangeo#327]
I'm getting internal server errors and, upon reload, HTTP 400 errors on pangeo.pydata.org.

I'm also seeing this after revoking and re-authorizing pangeo for Github OAuth and with a clean browser (cleared all cookies etc.)

Is anyone else seeing this?

**Comment by willirath** [comment]
The HTTP 400 status page states: "OAuth state missing from cookies"

**Comment by jhamman** [comment]
I was just able to get a notebook server on my first try. Maybe try again and report back?

**Comment by willirath** [comment]
Just tried from different machines and from different networks (institute's land line vs. my mobile phone).  Both result in a "500 - internal server error" followed by a 400 with the message "OAuth state missing from cookies".

**Comment by martindurant** [comment]
Hub log is showing exceptions like
```
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 328, in login_user
        authenticated = yield self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 227, in get_authenticated_user
        authenticated = yield self.authenticate(handler, data)
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/github.py", line 119, in authenticate
        access_token = resp_json['access_token']
    KeyError: 'access_token'
```
(presumably for *new* logins)

**Comment by martindurant** [comment]
Guess: github oauth credentials expired?

**Comment by willirath** [comment]
Some background on the time scales: I've worked on pangeo.pydata.org a little more than three weeks ago. Then, after the first unsuccessful login throwing the OAuth error I gave above, I revoked and re-authorized pangeo / mrocklin just like any completely new user would have to do.

**Comment by martindurant** [comment]
Yes, I am seeing that too, even if re-autherising. The full error log
```
E 2018-06-29 14:55:25.090 JupyterHub web:1591] Uncaught exception GET /hub/oauth_callback?code=9c8010e56fcbc92d8968&state=eyJzdGF0ZV9pZCI6ICI4Mzc0MjFiOTY4ZGM0MjlmOGQ5MTFkZTM5NWFhZjZiOCIsICJuZXh0X3VybCI6ICIvaHViL3VzZXIvbWFydGluZHVyYW50L2xhYj9yZWRpcmVjdHM9MSJ9 (10.128.0.40)
    HTTPServerRequest(protocol='http', host='pangeo.pydata.org', method='GET', uri='/hub/oauth_callback?code=9c8010e56fcbc92d8968&state=eyJzdGF0ZV9pZCI6ICI4Mzc0MjFiOTY4ZGM0MjlmOGQ5MTFkZTM5NWFhZjZiOCIsICJuZXh0X3VybCI6ICIvaHViL3VzZXIvbWFydGluZHVyYW50L2xhYj9yZWRpcmVjdHM9MSJ9', version='HTTP/1.1', remote_ip='10.128.0.40', headers={'X-Forwarded-Host': 'pangeo.pydata.org', 'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '80', 'X-Forwarded-For': '10.128.0.40', 'Cookie': '_ga=GA1.2.1472030524.1446566815; __utma=223778458.1472030524.1446566815.1490881059.1490884190.31; __utmc=223778458; __cfduid=db46ad62100414eceeacdf0e4386fe5c71521663066; _xsrf=2|7592ee4a|8be6146b927bab899a5a56ae6c3834f2|1529514331; oauthenticator-state="2|1:0|10:1530284120|20:oauthenticator-state|184:ZXlKemRHRjBaVjlwWkNJNklDSTRNemMwTWpGaU9UWTRaR00wTWpsbU9HUTVNVEZrWlRNNU5XRmhaalppT0NJc0lDSnVaWGgwWDNWeWJDSTZJQ0l2YUhWaUwzVnpaWEl2YldGeWRHbHVaSFZ5WVc1MEwyeGhZajl5WldScGNtVmpkSE05TVNKOQ==|76d76fd5e63c3a85021b331c82e378ca1039a59af3922c6aaa3fbc2515f3fddc"', 'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36', 'Upgrade-Insecure-Requests': '1', 'Connection': 'close', 'Host': 'pangeo.pydata.org'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 328, in login_user
        authenticated = yield self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 227, in get_authenticated_user
        authenticated = yield self.authenticate(handler, data)
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/github.py", line 119, in authenticate
        access_token = resp_json['access_token']
    KeyError: 'access_token'

[E 2018-06-29 14:55:25.093 JupyterHub log:114] {
      "X-Forwarded-Host": "pangeo.pydata.org",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "80",
      "X-Forwarded-For": "10.128.0.40",
      "Cookie": "_ga=GA1.2.1472030524.1446566815; __utma=223778458.1472030524.1446566815.1490881059.1490884190.31; __utmc=223778458; __cfduid=db46ad62100414eceeacdf0e4386fe5c71521663066; _xsrf=2|7592ee4a|8be6146b927bab899a5a56ae6c3834f2|1529514331; oauthenticator-state=\"2|1:0|10:1530284120|20:oauthenticator-state|184:ZXlKemRHRjBaVjlwWkNJNklDSTRNemMwTWpGaU9UWTRaR00wTWpsbU9HUTVNVEZrWlRNNU5XRmhaalppT0NJc0lDSnVaWGgwWDNWeWJDSTZJQ0l2YUhWaUwzVnpaWEl2YldGeWRHbHVaSFZ5WVc1MEwyeGhZajl5WldScGNtVmpkSE05TVNKOQ==|76d76fd5e63c3a85021b331c82e378ca1039a59af3922c6aaa3fbc2515f3fddc\"",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Accept-Encoding": "gzip, deflate",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "Host": "pangeo.pydata.org"
    }
[E 2018-06-29 14:55:25.093 JupyterHub log:122] 500 GET /hub/oauth_callback?code=9c8010e56fcbc92d8968&state=eyJzdGF0ZV9pZCI6ICI4Mzc0MjFiOTY4ZGM0MjlmOGQ5MTFkZTM5NWFhZjZiOCIsICJuZXh0X3VybCI6ICIvaHViL3VzZXIvbWFydGluZHVyYW50L2xhYj9yZWRpcmVjdHM9MSJ9 (@10.128.0.40) 185.36ms
```

**Comment by rabernat** [comment]
I was able to access just fine this morning.

I wonder what is going on here...

**Comment by martindurant** [comment]
@rabernat , suspect this might only be happening where the browser doesn't have cached credentials, maybe worth trying in a new session.

I recall getting a security email from google a few days ago about possible exposure of some credential (service account?), which is why I am guessing some ID has been blocked. I'm not sure that it was related at all.

**Comment by mariusvniekerk** [comment]
Tried a different browser, same results

**Comment by tjcrone** [comment]
I can confirm that I am also getting a 500 when trying to log in to pangeo.pydata.org when my credentials are not cached. (I find this easiest to test by trying to connect using a private browser window.) I also see that the logs are indicating an OAuth token problem, well before the hub tries to launch my pod. So I'm thinking that maybe the GitHub client secret token may have been revoked, and may need to be regenerated and then pangeo needs to be upgraded with the new client secret. I don't think I have access to the project OAuth settings, so I cannot confirm that this is the issue. But it's worth looking at.

**Comment by jhamman** [comment]
I redeployed the cluster a few hours ago so let me know if there are still problems authenticating? I'm not positive but I don't think the service account stuff @martindurant mentioned is related. That had to do with pangeo-binder's credentials to the Google Container Registry.

**Comment by martindurant** [comment]
Worked just now for me

**Comment by willirath** [comment]
Works from here, too.
