### ISSUE TITLE
Issues trying to get running on TACC Wrangler

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#34]
Both Cheyenne and our local HPC cluster are down at the moment, and pangeo-GCP is not working yet. I need to do a dask distrubted demo tonight, so I am scrambling to get a solution.

I remembered I have a startup allocation on the XSEDE system [TACC Wrangler](https://www.tacc.utexas.edu/systems/wrangler)
> Wrangler is the most powerful data analysis system allocated in XSEDE. The system is designed for large scale data transfer, analytics, and sharing and provides flexible support for a wide range of software stacks and workflows. Its scalable design allows for growth in the number of users and data applications

Wrangler is actually an ideal place to test out pangeo. ([Wrangler user guide](https://portal.tacc.utexas.edu/user-guides/wrangler))

I am trying to get up and running, using the Cheyenne launch scripts as a template. I have encountered a number of issues along the way. I will post them here.

**Comment by rabernat** [comment]
The first issue I encountered was that `dask-mpi` is apparently not compatible with the `ibrun` mpi command that you are required to use on TACC systems:
```
$ ibrun dask-mpi
TACC: Starting up job 
/usr/local/bin/ibrun: line 161: getmode.sh: command not found
TACC: Could not determine MPI stack. Exiting!
```

This is not a dealbreaker for now, since I know numerous other ways to launch the cluster. However, it would be good to have a more universal solution.

**Comment by mrocklin** [comment]
This issue exists on Cheyenne as well.  Different implementations seem to have different keyword expectations.  My solution was to base things off of the mpich implementation available through conda.

     conda install mpi4py

**Comment by rabernat** [comment]
A second issue is that, when I specify `--interface ib0` to dask-scheduler, I can't connect to the bokeh. (Yes, this is a valid interface.) So I needed to remove this flag.

However, the workers still seem to work with `--interface ib0` and connect to the scheduler.

**Comment by rabernat** [comment]
A third issue is with `setup-jlab.py`. When I run this command, I get the following error in the worker log, and jupyterlab does not start. (I am using the environment.yml file from the pangeo repo.)

```
Traceback (most recent call last):
  File "/home/02823/rabernat/miniconda3/envs/pangeo/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/02823/rabernat/miniconda3/envs/pangeo/bin/jupyter-lab", line 6, in <module>
    sys.exit(jupyterlab.labapp.main())
  File "/home/02823/rabernat/miniconda3/envs/pangeo/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/02823/rabernat/miniconda3/envs/pangeo/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/02823/rabernat/miniconda3/envs/pangeo/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/02823/rabernat/miniconda3/envs/pangeo/lib/python3.6/site-packages/notebook/notebookapp.py", line 1366, in initialize
    self.init_configurables()
  File "/home/02823/rabernat/miniconda3/envs/pangeo/lib/python3.6/site-packages/notebook/notebookapp.py", line 1100, in init_configurables
    connection_dir=self.runtime_dir,
  File "/home/02823/rabernat/miniconda3/envs/pangeo/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/home/02823/rabernat/miniconda3/envs/pangeo/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/home/02823/rabernat/miniconda3/envs/pangeo/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/home/02823/rabernat/miniconda3/envs/pangeo/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/home/02823/rabernat/miniconda3/envs/pangeo/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/02823/rabernat/miniconda3/envs/pangeo/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/run/user/821211'
```

**Comment by mrocklin** [comment]
> A second issue is that, when I specify --interface ib0 to dask-scheduler, I can't connect to the bokeh. (Yes, this is a valid interface.) So I needed to remove this flag.

> However, the workers still seem to work with --interface ib0 and connect to the scheduler.

Probably the scheduler's Bokeh server is trying to use the address of the machine on the Infiniband network, but that network doesn't support HTTP connections (reasonably so).  I remember being a bit surprised that this worked on Cheyenne.  It's possible that we might need to specify a separate `--interface-bokeh` keyword?

cc @pitrou for advice

**Comment by mrocklin** [comment]
> A third issue is with setup-jlab.py. When I run this command, I get the following error in the worker log, and jupyterlab does not start. (I am using the environment.yml file from the pangeo repo.)

My guess is that we are running JLab from a directory that doesn't provide write permissions, but JLab needs to write something to disk.  I suspect that on Cheyenne the job scheduler ran commands from the directory from which they were submitted but that Wrangler runs them by default in some new temporary directory.  I'm not sure though.

**Comment by rabernat** [comment]
> My guess is that we are running JLab from a directory that doesn't provide write permissions, but JLab needs to write something to disk.

I tried adding a `cd $WORK` line to the job script ($WORK is a writeable user directory) before launching jupyter lab, but the problem persists. It is trying to write some file called `/run/user/821211`. I have no idea where this is coming from.

If I try to launch jupyter lab from an interactive session, it works fine.

I also tried with / without `--notebook-dir`: makes no difference.

**Comment by mrocklin** [comment]
At this point I would reach out to Jupyter folks and ask what's going on.  They seem to be pretty responsive on https://gitter.im/jupyter/jupyter , though I'm not sure where they prefer to receive questions like this.

**Comment by rabernat** [comment]
Now I am remembering something from my experience on habanero:
https://github.com/rabernat/dask_distributed_demo/blob/master/jobscript_notebook_and_scheduler.sh

The `JUPYTER_RUNTIME_DIR` environment variable needs to be set.

See #36

**Comment by rabernat** [comment]
It is working now! 😀 

Wrangler is an absolute beast! I can't believe how fast everything is going.
