### ISSUE TITLE
spawing problems with pangeo.pydata.org

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo#354]
Over the past week, pangeo.pydata.org has been very unreliable. Numerous 400 / 500 errors (similar to #327). Most recently, this is what I see in the hub log:

```
$ kubectl --namespace=pangeo logs hub-76f8d7f488-tcxgg
[I 2018-08-10 14:34:55.666 JupyterHub base:727] rabernat is pending spawn
[I 2018-08-10 14:35:11.136 JupyterHub base:722] Pending spawn for rabernat didn't finish in 10.0 seconds
[I 2018-08-10 14:35:11.136 JupyterHub base:727] rabernat is pending spawn
[I 2018-08-10 14:35:26.394 JupyterHub base:722] Pending spawn for rabernat didn't finish in 10.0 seconds
[I 2018-08-10 14:35:26.394 JupyterHub base:727] rabernat is pending spawn
[I 2018-08-10 14:35:28.304 JupyterHub base:722] Pending spawn for rabernat didn't finish in 10.0 seconds
[I 2018-08-10 14:35:28.304 JupyterHub base:727] rabernat is pending spawn
[I 2018-08-10 14:35:28.307 JupyterHub log:122] 200 GET /hub/user/rabernat/ (rabernat@10.23.98.1) 10007.42ms
[E 2018-08-10 14:36:20.791 JupyterHub user:427] Unhandled error starting rabernat's server: pod/jupyter-rabernat did not start in 300 seconds!
[E 2018-08-10 14:36:20.889 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7f9b8c2dcb00> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 995, in start
        timeout=self.start_timeout
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-rabernat did not start in 300 seconds!
    
[E 2018-08-10 14:36:20.889 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7f9b8c2dcb00> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 995, in start
        timeout=self.start_timeout
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-rabernat did not start in 300 seconds!
    
...repeated ad nauseum
```

I can run the following command to fix this broken state:
```
helm upgrade --force --recreate-pods jupyter pangeo/pangeo --version=$VERSION -f actual-secret-config.yaml -f jupyter-config.yaml
```

I have done this several times over the past week.

I am concerned about this situation but don't know what to do to fix it.

**Comment by jacobtomlinson** [comment]
This looks like it is either notebook pods failing to start or capacity issues.

Perhaps the cluster is not scaling as quickly as it needs to? We are having the same issues on our cluster at the moment.
