### ISSUE TITLE
500 errors again this morning

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#358]
![2018-08-15_8-00-44](https://user-images.githubusercontent.com/1872600/44147270-5ea5a7ea-a061-11e8-813a-710b001637bf.jpg)

(and yes, I did try starting my server again from http://pangeo.pydata.org/hub/home)

**Comment by rabernat** [comment]
What are the logs in your hub showing?

```
kubectl logs hub-??????
```

**Comment by rsignell-usgs** [comment]
@rabernat,  I'm getting these errors on pangeo.pydata.org, not pangeo.esipfed.org. I don't have the `kubeconfig` for pangeo.pydata.org, so I can't run `kubectl` on that cluster.

![2018-08-15_10-10-35](https://user-images.githubusercontent.com/1872600/44152432-88faa3e4-a073-11e8-80f1-81f3e6e8aa07.png)
![2018-08-15_10-12-15](https://user-images.githubusercontent.com/1872600/44152534-cc605598-a073-11e8-9a04-171f4e4e355c.png)

[wait 5 minutes...]

![2018-08-15_10-08-50](https://user-images.githubusercontent.com/1872600/44152458-9882ddf4-a073-11e8-9457-49e1a6d0e34d.png)

**Comment by rabernat** [comment]
Ah thanks for clarifying. It's the usual thing.

```
[I 2018-08-15 14:46:33.447 JupyterHub base:727] vntegeka is pending spawn
[I 2018-08-15 14:46:50.415 JupyterHub base:722] Pending spawn for vntegeka didn't finish in 10.0 seconds
[I 2018-08-15 14:46:50.415 JupyterHub base:727] vntegeka is pending spawn
[I 2018-08-15 14:47:07.422 JupyterHub base:722] Pending spawn for vntegeka didn't finish in 10.0 seconds
[I 2018-08-15 14:47:07.422 JupyterHub base:727] vntegeka is pending spawn
[I 2018-08-15 14:47:24.417 JupyterHub base:722] Pending spawn for vntegeka didn't finish in 10.0 seconds
[I 2018-08-15 14:47:24.418 JupyterHub base:727] vntegeka is pending spawn
[E 2018-08-15 14:47:26.130 JupyterHub user:427] Unhandled error starting vntegeka's server: pod/jupyter-vntegeka did not start in 300 seconds!
[E 2018-08-15 14:47:26.248 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7f93b00e2dd8> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 995, in start
        timeout=self.start_timeout
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-vntegeka did not start in 300 seconds!
    
[E 2018-08-15 14:47:26.249 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7f93b00e2dd8> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 995, in start
        timeout=self.start_timeout
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-vntegeka did not start in 300 seconds!
```

Let's work with @yuvipanda to try to get to the bottom of this!

**Comment by rabernat** [comment]
And @jacobtomlinson!

**Comment by jacobtomlinson** [comment]
Looking now. It looks like the notebooks do start successfully, however the Hub isn't aware.

```
» kubectl -n pangeo get po
NAME                                  READY     STATUS      RESTARTS   AGE
dask-adeajayi-kunle-f399a497-cc7qfl   0/1       Completed   0          15h
dask-adeajayi-kunle-f399a497-clbmps   0/1       Completed   0          15h
dask-rsignell-usgs-927016aa-87szkr    0/1       Completed   0          16h
dask-rsignell-usgs-927016aa-8f6m5d    0/1       Completed   0          16h
dask-rsignell-usgs-927016aa-8mg468    0/1       Completed   0          16h
dask-rsignell-usgs-927016aa-8sc8lr    0/1       Completed   0          16h
hub-76f8d7f488-c5p2g                  1/1       Running     1          5d
jupyter-adeajayi-2dkunle              1/1       Running     0          5h
jupyter-apawloski                     0/1       Pending     0          41s
jupyter-darothen-2dcc                 1/1       Running     0          35m
jupyter-gustavo-2dmarques             1/1       Running     0          31m
jupyter-ioanna-2di                    1/1       Running     0          2h
jupyter-jhamman                       1/1       Running     0          18m
jupyter-nickmortimer                  1/1       Running     0          3h
jupyter-rabernat                      1/1       Running     0          27m
jupyter-rsignell-2dusgs               1/1       Running     0          1h
jupyter-scottyhq                      0/1       Pending     0          14s
jupyter-stb2145                       1/1       Running     0          28m
jupyter-vntegeka                      1/1       Running     0          47m
proxy-64f95bb784-c8wgd                1/1       Running     0          5d
```

**Comment by rabernat** [comment]
And it's magically fixed.

**Comment by rabernat** [comment]
Can you just share the kubernetes command you used to restart only the hub?

**Comment by jacobtomlinson** [comment]
To list the pods

```
kubectl -n pangeo get pods
```

Then find the pod name for the hub and delete it

```
kubectl -n pangeo delete pod hub-76f8d7f488-c5p2g
```

One magic line would look like this

```
kubectl -n pangeo get po | grep hub | awk '{print $1}' | kubectl -n pangeo delete po
```

You can also visit the [admin page](http://pangeo.pydata.org/hub/admin) on Pangeo and click "Shutdown Hub".

**Comment by jacobtomlinson** [comment]
It looks like this issue is happening because Jupyter Hub is spawning notebooks but not keeping track of them. When looking at the list of running pods it doesn't line up with the admin page in Jupyter Hub.

**Comment by tjcrone** [comment]
I have been using very recent versions of Jupyter Hub in my many Pangeos, and continue to have issues just like this. Notebooks spawn, or don't sometimes, but the hub clearly looses track of who's what where. The only way to fix it is to redeploy (upgrade) Pangeo, or to delete the deployment and redeploy. I am not very far along figuring out why this is happening, but I'm pretty low on confidence that a more recent JHub is going to fix this.

**Comment by rabernat** [comment]
I just merged #56. @yuvipanda is optimistic that it will fix the issue. @tjcrone, I would recommend opening an issue in zero2jupyerhub if you think there is still a problem.

**Comment by tjcrone** [comment]
i think i'll just watch the issue. thanks.

**Comment by rabernat** [comment]
Still happening with the latest jupyterhub helm chart.

This has affected @chiara7, who was trying to log in unsuccessfully today.
