### ISSUE TITLE
Slow performance with Zarr data on polar.pangeo.io

### ISSUE THREAD

**Issue by NicWayand** [pangeo-data/pangeo#433]
I have a small (272MB) Zarr dataset on a google bucket, that I am trying to work with on polar.pangeo.io.

```
<xarray.Dataset>
Dimensions:        (fore_time: 72, init_end: 56, model: 6, x: 304, y: 448)
Coordinates:
  * fore_time      (fore_time) timedelta64[ns] 0 days 1 days 2 days 3 days ...
  * init_end       (init_end) datetime64[ns] 2018-02-01 2018-02-06 ...
    lat            (x, y) float64 dask.array<shape=(304, 448), chunksize=(152, 224)>
    lon            (x, y) float64 dask.array<shape=(304, 448), chunksize=(152, 224)>
  * model          (model) object 'Observed' 'gfdlsipn' 'rasmesrl' ...
Dimensions without coordinates: x, y
Data variables:
    mean_25km_1km  (init_end, model, fore_time, x, y) float64 dask.array<shape=(56, 6, 72, 304, 448), chunksize=(1, 1, 1, 304, 448)>
```

Using intake, I can lazy load the dataset fine. But when triggering computations to load the data, it is extremely slow (10's of mins, or just hangs...) vs. fast (1 min) on my local machine w/ 8 workers. 

The reproducible example is available at https://polar.pangeo.io, in the `Test_Zarr_Load_Times.ipynb` notebook. 

Likely culprits are:
1) Chuck size of the Zarr dataset. I have tried rechunking it to have larger chunks, but no difference.
2) Dask scheduling choices. In the example notebook, I have tried to test the main options I know of. The machines polar.pangeo.io uses are `n1-standard-4`.
3) Zarr is not a good format for this data? I saved it to a single netcdf file, and it totals 25GB! I am surprised it is so much larger than the Zarr size (272MB).

**Comment by alimanfoo** [comment]
Hi @NicWayand, thought I'd give this a try although I have no understanding of the data. I wanted to see if this could be due to latency involved in loading metadata, this has come up before and @martindurant has done work towards a solution (https://github.com/zarr-developers/zarr/pull/268). Couple of things came up though that surprised me (although maybe missing some important details)...

With the dask distributed cluster and client activated, I tried:

```
ds_SIT = intake.Catalog('./catalog.yaml').SIPN2_SIT.to_dask()
```

I thought this step would just setup zarr/dask/xarray interface to the data, but not actually compute anything. Hence I thought timing this step might give an indication of time due to loading metadata. However I watched the dask distributed dashboard and saw some dask work happening, which I wasn't expecting. This step took 29s, but as dask was doing some work, I'm not sure what that time is due to.

I then tried:

```
ds_SIT.mean_25km_1km.data.max().compute()
```

...but got a KilledWorker error, which I think is an indication that something went wrong with the computation, but the underlying exception is not propagated.

Sorry this is not much help, but if anyone else has ideas about how to tease things apart and investigate whether slow performance is due to metadata loading or other factors, happy to follow up.

**Comment by NicWayand** [comment]
Hi @alimanfoo, thanks for trying it out. To confirm, I also get a KilledWorker error using the KubeCluster.

**Comment by mrocklin** [comment]
https://stackoverflow.com/questions/46691675/what-do-killedworker-exceptions-mean-in-dask

**Comment by rabernat** [comment]
I have a hunch that this is related to gcsfs authentication. This is the first dataset we have tried to read this way that is in a private bucket belonging to a different project. The other datasets in your catalog living in the regular pangeo-data bucket (e.g. `NSIDC_0051`) work fine.

**Comment by rabernat** [comment]
I think I have confirmed that the problem is related to credentials.

Here is the intake entry for this dataset:
```
{'plugin': 'zarr',
 'description': 'Sea Ice Prediction Network Phase 2 (SIPN2) Sea ice thickness forecasts and IceBridge observations.',
 'direct_access': 'forbid',
 'metadata': {'url': 'https://atmos.uw.edu/sipn',
  'tags': ['sea ice', 'satellite', 'forecast'],
  'cache': []},
 'args': {'storage_options': {'project': 'sipn2-pangeo',
   'token': 'browser',
   'access': 'read_only'},
  'urlpath': 'gcs://sipn-data-hi/hi.zarr',
  'metadata': {'url': 'https://atmos.uw.edu/sipn',
   'tags': ['sea ice', 'satellite', 'forecast'],
   'cache': [],
   'catalog_dir': '/home/jovyan/.'}}}
```

From polar.pangeo.io
```python
import gcsfs
# create a gcsfs session using a `browser` token
gcs_sit_browser = gcsfs.GCSFileSystem(project='sipn2-pangeo', token='browser')
# now create one using a cached token
gcs_sit_cache = gcsfs.GCSFileSystem(project='sipn2-pangeo', token='cache')
# create gcsmaps to the dataset using each gcs object
gcsmap_sit_browser = gcsfs.GCSMap('sipn-data-hi/hi.zarr', gcs=gcs_sit_browser)
gcsmap_sit_cache = gcsfs.GCSMap('sipn-data-hi/hi.zarr', gcs=gcs_sit_cache)
# define a function to get the zarr group metadata, a test for whether we can actually read data
def get_group(gcsmap):
    return gcsmap['.zgroup']
# run it locally and verify it works
print(get_group(gcsmap_sit_browser))
print(get_group(gcsmap_sit_cache))
```
this gives
```
b'{\n    "zarr_format": 2\n}'
b'{\n    "zarr_format": 2\n}'
```

Now I create a cluster and try the same thing
```python
from dask.distributed import Client, progress
from dask_kubernetes import KubeCluster
cluster = KubeCluster(n_workers=5)
client = Client(cluster)

# try with browser token
client.run(get_group, gcsmap_sit_browser)
```
raises a long error ending with
```
Exception: EOF when reading a line
Future exception was never retrieved
future: <Future finished exception=Exception('EOF when reading a line',)>
Traceback (most recent call last):
  File "/srv/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/srv/conda/lib/python3.6/site-packages/distributed/utils.py", line 226, in quiet
    yield task
  File "/srv/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/srv/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/srv/conda/lib/python3.6/site-packages/distributed/scheduler.py", line 2317, in send_message
    resp = yield send_recv(comm, close=True, serializers=serializers, **msg)
  File "/srv/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/srv/conda/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/srv/conda/lib/python3.6/site-packages/distributed/core.py", line 448, in send_recv
    raise Exception(response['text'])
Exception: EOF when reading a line
```
I believe the clients are trying to get the text input for the token!

If we try with the cache token, we get
```python
client.run(get_group, gcsmap_sit_cache)
```
```
...
/srv/conda/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

/srv/conda/bin/dask-worker in get_group()
      1 def get_group(gcsmap):
----> 2     return gcsmap['.zgroup']

/srv/conda/lib/python3.6/site-packages/gcsfs/mapping.py in __getitem__()
     64         key = self._key_to_str(key)
     65         try:
---> 66             with self.gcs.open(key, 'rb') as f:
     67                 result = f.read()
     68         except (IOError, OSError):

<decorator-gen-28> in open()

/srv/conda/lib/python3.6/site-packages/gcsfs/core.py in _tracemethod()
     49         logger.log(logging.DEBUG - 1, tb_io.getvalue())
     50 
---> 51     return f(self, *args, **kwargs)
     52 
     53 

/srv/conda/lib/python3.6/site-packages/gcsfs/core.py in open()
    969         if 'b' in mode:
    970             return GCSFile(self, path, mode, block_size, consistency=const,
--> 971                            metadata=metadata)
    972         else:
    973             mode = mode.replace('t', '') + 'b'

<decorator-gen-31> in __init__()

/srv/conda/lib/python3.6/site-packages/gcsfs/core.py in _tracemethod()
     49         logger.log(logging.DEBUG - 1, tb_io.getvalue())
     50 
---> 51     return f(self, *args, **kwargs)
     52 
     53 

/srv/conda/lib/python3.6/site-packages/gcsfs/core.py in __init__()
   1093             raise NotImplementedError('File mode not supported')
   1094         if mode == 'rb':
-> 1095             self.details = gcsfs.info(path)
   1096             self.size = self.details['size']
   1097         else:

<decorator-gen-17> in info()

/srv/conda/lib/python3.6/site-packages/gcsfs/core.py in _tracemethod()
     49         logger.log(logging.DEBUG - 1, tb_io.getvalue())
     50 
---> 51     return f(self, *args, **kwargs)
     52 
     53 

/srv/conda/lib/python3.6/site-packages/gcsfs/core.py in info()
    827 
    828         try:
--> 829             return self._get_object(path)
    830         except FileNotFoundError:
    831             logger.debug("info FileNotFound at path: %s", path)

<decorator-gen-3> in _get_object()

/srv/conda/lib/python3.6/site-packages/gcsfs/core.py in _tracemethod()
     49         logger.log(logging.DEBUG - 1, tb_io.getvalue())
     50 
---> 51     return f(self, *args, **kwargs)
     52 
     53 

/srv/conda/lib/python3.6/site-packages/gcsfs/core.py in _get_object()
    517 
    518         result = self._process_object(bucket, self._call('get', 'b/{}/o/{}',
--> 519                                                          bucket, key))
    520 
    521         return result

<decorator-gen-2> in _call()

/srv/conda/lib/python3.6/site-packages/gcsfs/core.py in _tracemethod()
     49         logger.log(logging.DEBUG - 1, tb_io.getvalue())
     50 
---> 51     return f(self, *args, **kwargs)
     52 
     53 

/srv/conda/lib/python3.6/site-packages/gcsfs/core.py in _call()
    456             try:
    457                 time.sleep(2**retry - 1)
--> 458                 r = meth(self.base + path, params=kwargs, json=json)
    459                 validate_response(r, path)
    460                 break

/srv/conda/lib/python3.6/site-packages/requests/sessions.py in get()
    523 
    524         kwargs.setdefault('allow_redirects', True)
--> 525         return self.request('GET', url, **kwargs)
    526 
    527     def options(self, url, **kwargs):

/srv/conda/lib/python3.6/site-packages/google/auth/transport/requests.py in request()
    195         request_headers = headers.copy() if headers is not None else {}
    196 
--> 197         self.credentials.before_request(
    198             self._auth_request, method, url, request_headers)
    199 

AttributeError: 'AuthorizedSession' object has no attribute 'credentials'
```

Which means the credentials are not making it to the client.

**Comment by rabernat** [comment]
This is a case for @martindurant!

**Comment by rabernat** [comment]
A few comments on the run time.

Your data has very small chunks:
```
mean_25km_1km  (init_end, model, fore_time, x, y) float64 dask.array<shape=(56, 6, 72, 304, 448), chunksize=(1, 1, 1, 304, 448)>
```

The time to load a single chunk is few hundred ms
```python
>>> %time ds_sit.mean_25km_1km[-1, -1, -1].values
CPU times: user 29 ms, sys: 2 ms, total: 31 ms
Wall time: 337 ms
```

Most of this is overhead associated with making the http connection to gcs. This has to be done for each chunk. So the serial run time in minutes would be `56*6*72 * 0.33 / 60` or 133 minutes.

We can speed this up by resolving the distributed credentials issue above and parallelizing via the cluster. But I also think your chunk sizes are much too small. We generally aim for chunks in the 10-100MB range. Yours are more like 1MB.

**Comment by martindurant** [comment]
If you are using `'token': 'browser'`, you will need to copy the `~/.gcs_tokens` file to all of the worker machines. 
You *can* distribute the credentials via direct serialisation (i.e., unsecurely, but only within the cluster), but this is not the norm. I forget where that method is described, I think a gcsfs issue.
(Sorry, I am at pydataNY, so my response time may be longer than usual)

**Comment by mrocklin** [comment]
@martindurant do you have any thoughts on how we can direct users to
correct behavior here?  We probably need to make this process more robust
to user inexperience.

**Comment by martindurant** [comment]
I am not sure, because the gcsfs docs don't really mention talk about distributed operation. The text at http://docs.dask.org/en/latest/remote-data-services.html#google-cloud-storage is probably the right place (and I see it looks pretty outdated), but I don't know whether users will naturally find that.

**Comment by mrocklin** [comment]
When you have the time, I think that this would be a useful thing for you
to think about.  Raising errors that direct users to what is wrong in cases
like these is probably important if we want to move these workflows to less
skilled users.

**Comment by martindurant** [comment]
Quick comment on the "up-front" time when accessing the data-set: this is down partly to reading metadata (as discussed elsewhere), but I think will also get all of the coordinate arrays. In this case, the coordinate arrays are also chunked in very small pieces, which accounts for this step also taking longer than expected.

**Comment by martindurant** [comment]
The following seems like a good start, but yes, I'll clean up that bit of documentation too.
```
--- a/gcsfs/core.py
+++ b/gcsfs/core.py
@@ -434,6 +434,8 @@ class GCSFileSystem(object):
         else:
             self.__getattribute__('_connect_' + method)()
             self.method = method
+        if self.session is None:
+            raise RuntimeError("Authentication Failed")

```

**Comment by NicWayand** [comment]
Thank you all for your help on this issue!

Looks like I forgot to update the `catalog.yaml` to make the SIPN2_SIT dataset public. The token is now anon if you restart your server on polar.pangeo.io

I rechunked it to `{'fore_time': 10, 'init_end': 10, 'model': 1, 'x': 304, 'y': 448}` (approx x100) and re-uploaded the dataset. But now upon loading it on polar.pangeo.io w/ intake:

`ds_SIT = intake.Catalog('./catalog.yaml').SIPN2_SIT.to_dask()`

Gives:

`NotImplementedError: Specified zarr chunks (10, 1, 10, 304, 448) would overlap multiple dask chunks ((10, 10, 10, 10, 10, 6), (1, 1, 1, 1, 1, 1), (10, 10, 10, 10, 10, 10, 10, 2), (304,), (448,)). This is not implemented in xarray yet.  Consider rechunking the data using `chunk()` or specifying different chunks in encoding.
`

Which appears related to https://github.com/pydata/xarray/pull/2487 
(note I am using xarray version 0.10.8)

**Comment by rabernat** [comment]
One workaround, until pydata/xarray#2487 is merged, would be to rechunk using exact divisors of the data dimensions. For example:
```
{'fore_time': 8, 'init_end': 8, 'model': 1, 'x': 304, 'y': 448}
```

**Comment by NicWayand** [comment]
The only remaining issue is that any private datasets that require the `browser` token, currently do not work with a cluster (Currently raising a killedworker). And if I understand @martindurant's [issue ](https://github.com/dask/dask/pull/4109) correctly, it will just throw a more descriptive error). 

Does Pangeo want to support private datasets? On one hand its against the open source ideals, but on the other it would be more inclusive to groups working with restrictive/beta datasets. If the consensus is yes, i'll raise a separate issue.

**Comment by martindurant** [comment]
@NicWayand , you should read http://docs.dask.org/en/latest/remote-data-services.html#google-cloud-storage , which I updated in a way which I hope makes sense to you.
