### ISSUE TITLE
Try out the dev branch of dask-kubernetes

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#562]
@yuvipanda and I recently switched dask-kubernetes to use an async-friendly kubernetes library.  This is in service of managing clusters through the dask-labextension sidebar.  

During this refactor we uncovered some bugs that I *suspect* were already in master, but am not entirely sure.  In particular these come up with rapidly scaling clusters up and down, such as is sometimes common when in adaptive mode.  

If folks are willing, I encourage them to point pangeo deployments to 

    pip install https://github.com/dask/dask-kubernetes@dev

I *think* that everything should run just fine, but would be curious to hear any feedback.

**Comment by scottyhq** [comment]
thanks @mrocklin. I've just given this a try on a pangeo binder (https://github.com/scottyhq/pangeo-binder-test/tree/daskdev) and get an error when launching a cluster 'the old way'. injecting a cluster via the dask extension seems to be working, but i haven't had time to do much testing...

```python
cluster = KubeCluster(n_workers=10)
cluster
```

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-28229275e681> in <module>
      1 # Select 10 'workers' under 'manual scaling' menu below and click 'Scale'
      2 # Click on the 'Dashboard link' to monitor calculation progress
----> 3 cluster = KubeCluster(n_workers=10)
      4 cluster

/srv/conda/lib/python3.6/site-packages/dask_kubernetes/core.py in __init__(self, pod_template, name, namespace, n_workers, host, port, env, auth, asynchronous, **kwargs)
    235             )
    236 
--> 237         self.start()
    238 
    239     @property

/srv/conda/lib/python3.6/site-packages/dask_kubernetes/core.py in start(self)
    269             self._started = self._start()
    270         else:
--> 271             return self.sync(self._start)
    272 
    273     def __await__(self):

/srv/conda/lib/python3.6/site-packages/dask_kubernetes/core.py in sync(self, func, *args, **kwargs)
    373 
    374     def sync(self, func, *args, **kwargs):
--> 375         return self.cluster.sync(func, *args, **kwargs)
    376 
    377     async def _pods(self):

/srv/conda/lib/python3.6/site-packages/distributed/deploy/local.py in sync(self, func, *args, **kwargs)
    170             return future
    171         else:
--> 172             return sync(self.loop, func, *args, **kwargs)
    173 
    174     def start(self, **kwargs):

/srv/conda/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    275             e.wait(10)
    276     if error[0]:
--> 277         six.reraise(*error[0])
    278     else:
    279         return result[0]

/srv/conda/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/srv/conda/lib/python3.6/site-packages/distributed/utils.py in f()
    260             if timeout is not None:
    261                 future = gen.with_timeout(timedelta(seconds=timeout), future)
--> 262             result[0] = yield future
    263         except Exception as exc:
    264             error[0] = sys.exc_info()

/srv/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1131 
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:
   1135                         self.had_exception = True

/srv/conda/lib/python3.6/site-packages/dask_kubernetes/core.py in _start(self)
    263 
    264         if self.n_workers:
--> 265             await self.scale(self.n_workers)
    266 
    267     def start(self):

TypeError: object NoneType can't be used in 'await' expression
```

**Comment by mrocklin** [comment]
Thanks @scottyhq .  This has been fixed.  Things seem a little bit better when I try your binder now (though I had to bump the version to the recent commit)

**Comment by jhamman** [comment]
@mrocklin - I tried this out a few days ago and things didn't go so smoothly. [![Binder](https://binder.pangeo.io/badge_logo.svg)](https://binder.pangeo.io/v2/gh/jhamman/pangeo_test_binder/dask_dev)

I seem to be getting the following error when calling the `KubeCluster.scale` method:

```python-traceback
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x7f0d6d301e48>>, <Task finished coro=<KubeCluster._scale_up() done, defined at /srv/conda/envs/notebook/lib/python3.6/site-packages/dask_kubernetes/core.py:510> exception=AttributeError("'V1Pod' object has no attribute 'openapi_types'",)>)
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/srv/conda/envs/notebook/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/srv/conda/envs/notebook/lib/python3.6/site-packages/dask_kubernetes/core.py", line 531, in _scale_up
    for _ in range(n - len(pods))
  File "/srv/conda/envs/notebook/lib/python3.6/site-packages/kubernetes_asyncio/client/api_client.py", line 156, in __call_api
    body = self.sanitize_for_serialization(body)
  File "/srv/conda/envs/notebook/lib/python3.6/site-packages/kubernetes_asyncio/client/api_client.py", line 220, in sanitize_for_serialization
    for attr, _ in six.iteritems(obj.openapi_types)
AttributeError: 'V1Pod' object has no attribute 'openapi_types'
```
