### ISSUE TITLE
Upgrading a pangeo

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#625]
How can I upgrade a pangeo while keeping it's resources intact? 

I am working with a deployment on GCP, that was set up using the instructions in the [setup guide](https://github.com/pangeo-data/pangeo/tree/master/gce/setup-guide)

I tried getting the new version of the helm chart, by rerunning the `gce-pangeo-environment.sh` script with the new helm chart version string and then ran `4_upgrade_helm.sh` again, to implement this change into our cluster, but that does not seem to have done the trick. Instead, I am now getting an error starting the hub pod.

**Comment by jhamman** [comment]
I typically upgrade with the following command:

```shell
deployment=prod
helm upgrade --install --namespace=${deployment} ${deployment} pangeo \
    --version=${version} \
    -f ../deploy/${deployment}.yaml \
    -f ../secrets/${deployment}.yaml
```

This will only upgrade those resources/services that have changed since the last deployment. 

> I am now getting an error starting the hub pod.

Can you report the error you're seeing?

**Comment by arokem** [comment]
But this means that you stay with the same version of the helmchart, right? So, if the docker image that was used for this deployment is updated (e.g.,  some new fancy capability is added), this will not propagate to this deployment. Is that right? 

Regarding the errors: in the first phase, it was timing out. Then, it was complaining that it couldn't find `start-singleuser.sh`and now it's completely down, with the hub in a `CrashLoopBackOff` state.

**Comment by arokem** [comment]
A bit more information here. Running `kubectl logs` on the hub pod shows the following stack trace:

```
[I 2019-05-15 15:39:55.309 JupyterHub app:1667] Using Authenticator: oauthenticator.github.GitHubOAuthenticator-0.8.0
[I 2019-05-15 15:39:55.309 JupyterHub app:1667] Using Spawner: kubespawner.spawner.KubeSpawner
[I 2019-05-15 15:39:55.310 JupyterHub app:1014] Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
[I 2019-05-15 15:39:55.326 JupyterHub dbutil:125] Upgrading sqlite:///jupyterhub.sqlite
[I 2019-05-15 15:39:55.327 JupyterHub dbutil:105] Backing up jupyterhub.sqlite => jupyterhub.sqlite.2019-05-15-153955
[I 2019-05-15 15:39:55.795 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
[I 2019-05-15 15:39:55.796 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
FAILED: Can't locate revision identified by '4dc2d5a8c53c'
[E 2019-05-15 15:39:55.800 alembic.util.messaging messaging:56] Can't locate revision identified by '4dc2d5a8c53c'
[E 2019-05-15 15:39:55.918 JupyterHub app:1952]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1949, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1674, in initialize
        self.init_db()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1071, in init_db
        dbutil.upgrade_if_needed(self.db_url, log=self.log)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/dbutil.py", line 130, in upgrade_if_needed
        upgrade(db_url)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/dbutil.py", line 89, in upgrade
        ['alembic', '-c', alembic_ini, 'upgrade', revision]
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['alembic', '-c', '/tmp/tmps1qo6bv7/alembic.ini', 'upgrade', 'head']' returned non-zero exit status 255.
```

**Comment by jhamman** [comment]
Can you share what you've changed (in diff form)? Maybe checkout out the [helm diff plugin](https://github.com/databus23/helm-diff). It seems like JupyterHub's sql database is having trouble updating.

**Comment by arokem** [comment]
OK - I think that I have managed to resolve my issues by tearing it all down and starting a new one. Closing.

**Comment by arokem** [comment]
Sorry. Reopening. As soon as I upgraded the cluster (to try to use my own docker image, see #626), I ran into this error again. Here's the full helm diff (I used `helm diff upgrade pangeohub pangeo/pangeo` to get it):

```


pangeo, hub-secret, Secret (v1) has changed:
  # Source: pangeo/charts/jupyterhub/templates/hub/secret.yaml
  kind: Secret
  apiVersion: v1
  metadata:
    name: hub-secret
    labels:
      component: hub
      app: jupyterhub
      release: pangeohub
-     chart: jupyterhub-0.7.0
+     chart: jupyterhub-0.8.0
      heritage: Tiller
  type: Opaque
  data:
    proxy.token: "YjlkYmZjZDdlYzY3NDgwNGVjOGVhMjNmMjc0OGZjMmFmYmE1NDYwZDc5ODAzYTgyNjEzNGE5NGVmYTU1NWRlNw=="
+   values.yaml: "YXV0aDoKICBnaXRodWI6CiAgICBjbGllbnRTZWNyZXQ6IDlhYTU3YjAxY2EzYmNmYTc3YzNmYjUzYWE4ZDliYWIwYTdkNThmNzkKaHViOgogIHNlcnZpY2VzOiB7fQo="
pangeo, hub-config, ConfigMap (v1) has changed:
  # Source: pangeo/charts/jupyterhub/templates/hub/configmap.yaml
  kind: ConfigMap
  apiVersion: v1
  metadata:
    name: hub-config
    labels:
      component: hub
      app: jupyterhub
      release: pangeohub
-     chart: jupyterhub-0.7.0
+     chart: jupyterhub-0.8.0
      heritage: Tiller
  data:
-   cull.enabled: "true"
-   cull.users: "false"
-   cull.timeout: "1200"
-   cull.every: "600"
-   cull.concurrency: "10"
-   cull.max-age: "0"
-   auth.type: "github"
-   auth.state.enabled: "false"
-   auth.admin.access: "true"
-   auth.admin.users: |
-     - arokem
-     - jhamman
-   auth.scopes: |
-     - read:user
-   auth.github.client-id: "cd83a79fd7ea3546f4c3"
-   auth.github.client-secret: "9aa57b01ca3bcfa77c3fb53aa8d9bab0a7d58f79"
-   auth.github.callback-url: "http://learning2learn.pangeo.io/hub/oauth_callback"
-   auth.github.org_whitelist: |
-     - learning-2-learn
-   singleuser.network-tools.image.name: "jupyterhub/k8s-network-tools"
-   singleuser.network-tools.image.tag: "0.7.0"
-   singleuser.cloud-metadata: |
-     enabled: true
-     ip: 169.254.169.254
-   singleuser.start-timeout: "300"
-   singleuser.image-pull-policy: "IfNotPresent"
-   singleuser.cmd: "jupyter-labhub"
-   singleuser.default-url: "/lab"
-   singleuser.events: "true"
-   singleuser.uid: "1000"
-   singleuser.fs-gid: "100"
-   singleuser.service-account-name: "daskkubernetes"
-   singleuser.node-selector: "{}"
-   singleuser.storage.type: "dynamic"
-   singleuser.storage.home_mount_path: "/home/jovyan"
-   singleuser.storage.extra-volumes: "[{\"hostPath\":{\"path\":\"/dev/fuse\"},\"name\":\"fuse\"}]"
-   singleuser.storage.extra-volume-mounts: "[{\"mountPath\":\"/dev/fuse\",\"name\":\"fuse\"}]"
-   singleuser.storage.capacity: "10Gi"
-   singleuser.storage.dynamic.pvc-name-template: "claim-{username}{servername}"
-   singleuser.storage.dynamic.volume-name-template: "volume-{username}{servername}"
-   singleuser.storage.dynamic.storage-access-modes: "[ReadWriteOnce]"
-   singleuser.memory.limit: "14G"
-   singleuser.memory.guarantee: "4G"
-   singleuser.cpu.limit: "4"
-   singleuser.cpu.guarantee: "1"
-   singleuser.extra-labels: |
-     hub.jupyter.org/network-access-hub: "true"
-   singleuser.extra-env: |
-     "EXTRA_PIP_PACKAGES": "h5py mne tensorflow"
-     "GCSFUSE_BUCKET": "learning2learn"
-   kubespawner.common-labels: |
-     app: jupyterhub
-     release: pangeohub
-     chart: jupyterhub-0.7.0
-     heritage: jupyterhub
-   hub.allow-named-servers: "false"
-   hub.concurrent-spawn-limit: "64"
-   hub.consecutive-failure-limit: "5"
-   hub.extra-config.customPodHook.py: |
-     from kubernetes import client
-     def modify_pod_hook(spawner, pod):
-         pod.spec.containers[0].security_context = client.V1SecurityContext(
-             privileged=True,
-             capabilities=client.V1Capabilities(
-                 add=['SYS_ADMIN']
-             )
-         )
-         return pod
-     c.KubeSpawner.modify_pod_hook = modify_pod_hook
-     c.JupyterHub.logo_file = '/usr/local/share/jupyterhub/static/custom/images/logo.png'
-     c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/',
-                                   '/usr/local/share/jupyterhub/templates/']
-     
-   hub.base_url: "/"
-   hub.db_url: "sqlite:///jupyterhub.sqlite"
-   debug.enabled: "false"
+   values.yaml: |
+     Chart:
+       Name: jupyterhub
+       Version: 0.8.0
+     Release:
+       Name: pangeohub
+       Namespace: pangeo
+       Service: Tiller
+     auth:
+       admin:
+         access: true
+         users:
+         - arokem
+         - jhamman
+       dummy:
+         password: null
+       github:
+         callbackUrl: http://learning2learn.pangeo.io/hub/oauth_callback
+         clientId: cd83a79fd7ea3546f4c3
+         org_whitelist:
+         - learning-2-learn
+       ldap:
+         dn:
+           search: {}
+           user: {}
+         user: {}
+       scopes:
+       - read:user
+       state:
+         enabled: false
+       type: github
+       whitelist:
+         users: null
+     cull:
+       concurrency: 10
+       enabled: true
+       every: 600
+       maxAge: 0
+       timeout: 1200
+       users: false
+     custom: {}
+     debug:
+       enabled: false
+     hub:
+       activeServerLimit: null
+       allowNamedServers: false
+       annotations: {}
+       baseUrl: /
+       concurrentSpawnLimit: 64
+       consecutiveFailureLimit: 5
+       db:
+         password: null
+         pvc:
+           accessModes:
+           - ReadWriteOnce
+           annotations: {}
+           selector: {}
+           storage: 1Gi
+           storageClassName: null
+           subPath: null
+         type: sqlite-pvc
+         upgrade: null
+         url: null
+       deploymentStrategy:
+         rollingUpdate: null
+         type: Recreate
+       extraConfig:
+         customPodHook: |
+           from kubernetes import client
+           def modify_pod_hook(spawner, pod):
+               pod.spec.containers[0].security_context = client.V1SecurityContext(
+                   privileged=True,
+                   capabilities=client.V1Capabilities(
+                       add=['SYS_ADMIN']
+                   )
+               )
+               return pod
+           c.KubeSpawner.modify_pod_hook = modify_pod_hook
+           c.JupyterHub.logo_file = '/usr/local/share/jupyterhub/static/custom/images/logo.png'
+           c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/',
+                                         '/usr/local/share/jupyterhub/templates/']
+       extraContainers: []
+       extraVolumeMounts:
+       - mountPath: /usr/local/share/jupyterhub/custom_templates
+         name: custom-templates
+         subPath: pangeo-custom-jupyterhub-templates/templates
+       - mountPath: /usr/local/share/jupyterhub/static/custom
+         name: custom-templates
+         subPath: pangeo-custom-jupyterhub-templates/assets
+       extraVolumes:
+       - gitRepo:
+           repository: https://github.com/pangeo-data/pangeo-custom-jupyterhub-templates.git
+           revision: b09721bb1a1248dc115730d3c8a791600eae257e
+         name: custom-templates
+       fsGid: 1000
+       image:
+         name: jupyterhub/k8s-hub
+         tag: 0.8.0
+       imagePullPolicy: IfNotPresent
+       imagePullSecret:
+         email: null
+         enabled: false
+         password: null
+         registry: null
+         username: null
+       labels: {}
+       networkPolicy:
+         egress:
+         - to:
+           - ipBlock:
+               cidr: 0.0.0.0/0
+         enabled: false
+       nodeSelector: {}
+       pdb:
+         enabled: true
+         minAvailable: 1
+       publicURL: null
+       resources:
+         requests:
+           cpu: 200m
+           memory: 512Mi
+       service:
+         annotations: {}
+         loadBalancerIP: null
+         ports:
+           nodePort: null
+         type: ClusterIP
+       services: {}
+       uid: 1000
+     scheduling:
+       corePods:
+         nodeAffinity:
+           matchNodePurpose: prefer
+       podPriority:
+         defaultPriority: 0
+         enabled: false
+         globalDefault: false
+         userPlaceholderPriority: -10
+       userPlaceholder:
+         enabled: true
+         replicas: 0
+       userPods:
+         nodeAffinity:
+           matchNodePurpose: prefer
+       userScheduler:
+         enabled: false
+         image:
+           name: gcr.io/google_containers/kube-scheduler-amd64
+           tag: v1.11.2
+         logLevel: 4
+         nodeSelector: {}
+         pdb:
+           enabled: true
+           minAvailable: 1
+         replicas: 1
+         resources:
+           requests:
+             cpu: 50m
+             memory: 256Mi
+     singleuser:
+       cloudMetadata:
+         enabled: true
+         ip: 169.254.169.254
+       cmd: jupyter-labhub
+       cpu:
+         guarantee: 1
+         limit: 4
+       defaultUrl: /lab
+       events: true
+       extraAnnotations: {}
+       extraContainers: []
+       extraEnv:
+         EXTRA_PIP_PACKAGES: h5py mne tensorflow
+         GCSFUSE_BUCKET: learning2learn
+       extraLabels:
+         hub.jupyter.org/network-access-hub: "true"
+       extraNodeAffinity:
+         preferred: []
+         required: []
+       extraPodAffinity:
+         preferred: []
+         required: []
+       extraPodAntiAffinity:
+         preferred: []
+         required: []
+       extraResource:
+         guarantees: {}
+         limits: {}
+       extraTolerations: []
+       fsGid: 100
+       image:
+         name: arokem/learning2learn
+         pullPolicy: IfNotPresent
+         tag: 2019-05-21
+       imagePullSecret:
+         email: null
+         enabled: false
+         registry: null
+         username: null
+       initContainers: []
+       lifecycleHooks: null
+       memory:
+         guarantee: 4G
+         limit: 14G
+       networkPolicy:
+         egress:
+         - to:
+           - ipBlock:
+               cidr: 0.0.0.0/0
+               except:
+               - 169.254.169.254/32
+         enabled: false
+       networkTools:
+         image:
+           name: jupyterhub/k8s-network-tools
+           tag: 0.8.0
+       nodeSelector: {}
+       serviceAccountName: daskkubernetes
+       startTimeout: 300
+       storage:
+         capacity: 10Gi
+         dynamic:
+           pvcNameTemplate: claim-{username}{servername}
+           storageAccessModes:
+           - ReadWriteOnce
+           storageClass: null
+           volumeNameTemplate: volume-{username}{servername}
+         extraLabels: {}
+         extraVolumeMounts:
+         - mountPath: /dev/fuse
+           name: fuse
+         extraVolumes:
+         - hostPath:
+             path: /dev/fuse
+           name: fuse
+         homeMountPath: /home/jovyan
+         static:
+           pvcName: null
+           subPath: '{username}'
+         type: dynamic
+       uid: 1000
pangeo, hub, Role (rbac.authorization.k8s.io) has changed:
  # Source: pangeo/charts/jupyterhub/templates/hub/rbac.yaml
  kind: Role
- apiVersion: rbac.authorization.k8s.io/v1beta1
+ apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: hub
    labels:
      component: hub
      app: jupyterhub
      release: pangeohub
-     chart: jupyterhub-0.7.0
+     chart: jupyterhub-0.8.0
      heritage: Tiller
  rules:
    - apiGroups: [""]       # "" indicates the core API group
      resources: ["pods", "persistentvolumeclaims"]
      verbs: ["get", "watch", "list", "create", "delete"]
    - apiGroups: [""]       # "" indicates the core API group
      resources: ["events"]
      verbs: ["get", "watch", "list"]
pangeo, proxy, Deployment (apps) has changed:
  # Source: pangeo/charts/jupyterhub/templates/proxy/deployment.yaml
- apiVersion: apps/v1beta2
+ apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: proxy
    labels:
      component: proxy
      app: jupyterhub
      release: pangeohub
-     chart: jupyterhub-0.7.0
+     chart: jupyterhub-0.8.0
      heritage: Tiller
  spec:
    replicas: 1
    selector:
      matchLabels:
        component: proxy
        app: jupyterhub
        release: pangeohub
    template:
      metadata:
        labels:
          component: proxy
          app: jupyterhub
          release: pangeohub
          hub.jupyter.org/network-access-hub: "true"
          hub.jupyter.org/network-access-singleuser: "true"
        annotations:
          # This lets us autorestart when the secret changes!
-         checksum/hub-secret: ef7d4dda340a240003156f8f62cc3a77ca412a2b7ad1bc5d9617478656964322
+         checksum/hub-secret: 1c4b289856cf93d72d8196046381d94b1f790f5a6b734a058fbf9ad44551aec6
          checksum/proxy-secret: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
      spec:
-       nodeSelector: {}
        terminationGracePeriodSeconds: 60
+       nodeSelector: {}
        affinity:
-         podAffinity:
+         nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
-             - weight: 1
-               podAffinityTerm:
-                 topologyKey: kubernetes.io/hostname
-                 labelSelector:
-                   matchExpressions:
-                     - key: component
-                       operator: In
-                       values: ['hub']
-                     - key: release
-                       operator: In
-                       values: ["pangeohub"]
+             - weight: 100
+               preference:
+                 matchExpressions:
+                   - key: hub.jupyter.org/node-purpose
+                     operator: In
+                     values: [core]
        containers:
          - name: chp
            image: jupyterhub/configurable-http-proxy:3.0.0
            command:
              - configurable-http-proxy
              - --ip=0.0.0.0
              - --api-ip=0.0.0.0
              - --api-port=8001
              - --default-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)
              - --error-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)/hub/error
              - --port=8000
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
            env:
              - name: CONFIGPROXY_AUTH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: hub-secret
                    key: proxy.token
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8000
                name: proxy-public
              - containerPort: 8001
                name: api
pangeo, hub, PodDisruptionBudget (policy) has changed:
  # Source: pangeo/charts/jupyterhub/templates/hub/pdb.yaml
  apiVersion: policy/v1beta1
  kind: PodDisruptionBudget
  metadata:
    name: hub
    labels:
      component: hub
      app: jupyterhub
      release: pangeohub
-     chart: jupyterhub-0.7.0
+     chart: jupyterhub-0.8.0
      heritage: Tiller
  spec:
    minAvailable: 1
    selector:
      matchLabels:
        component: hub
        app: jupyterhub
        release: pangeohub
pangeo, hub-db-dir, PersistentVolumeClaim (v1) has changed:
  # Source: pangeo/charts/jupyterhub/templates/hub/pvc.yaml
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: hub-db-dir
    labels:
      component: hub
      app: jupyterhub
      release: pangeohub
-     chart: jupyterhub-0.7.0
+     chart: jupyterhub-0.8.0
      heritage: Tiller
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "1Gi"
pangeo, daskkubernetes, ServiceAccount (v1) has changed:
  # Source: pangeo/templates/dask-kubernetes-rbac.yaml
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: daskkubernetes
    namespace: pangeo
    labels:
-     chart: pangeo-v0.1.1-c02878a
+     chart: pangeo-19.03.05
      component: daskkubernetes
      heritage: Tiller
      release: pangeohub
pangeo, hub, Service (v1) has changed:
  # Source: pangeo/charts/jupyterhub/templates/hub/service.yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: hub
    labels:
      component: hub
      app: jupyterhub
      release: pangeohub
-     chart: jupyterhub-0.7.0
+     chart: jupyterhub-0.8.0
      heritage: Tiller
+   annotations:
+     prometheus.io/scrape: "true"
+     prometheus.io/path: /hub/metrics
  spec:
    type: ClusterIP
    selector:
      component: hub
      app: jupyterhub
      release: pangeohub
    ports:
      - protocol: TCP
        port: 8081
        targetPort: 8081
pangeo, proxy-public, Service (v1) has changed:
  # Source: pangeo/charts/jupyterhub/templates/proxy/service.yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: proxy-public
    labels:
      component: proxy-public
      app: jupyterhub
      release: pangeohub
-     chart: jupyterhub-0.7.0
+     chart: jupyterhub-0.8.0
      heritage: Tiller
  spec:
    selector:
      # TODO: Refactor to utilize the helpers
      component: proxy
      release: pangeohub
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8000
        # allow proxy.service.nodePort for http
+     - name: https
+       port: 443
+       protocol: TCP
+       targetPort: 443
    type: LoadBalancer
    loadBalancerIP: 104.196.229.33
pangeo, proxy-api, Service (v1) has changed:
  # Source: pangeo/charts/jupyterhub/templates/proxy/service.yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: proxy-api
    labels:
      component: proxy-api
      app: jupyterhub
      release: pangeohub
-     chart: jupyterhub-0.7.0
+     chart: jupyterhub-0.8.0
      heritage: Tiller
  spec:
    selector:
      component: proxy
      app: jupyterhub
      release: pangeohub
    ports:
      - protocol: TCP
        port: 8001
        targetPort: 8001
pangeo, hub, Deployment (apps) has changed:
  # Source: pangeo/charts/jupyterhub/templates/hub/deployment.yaml
- apiVersion: apps/v1beta2
+ apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hub
    labels:
      component: hub
      app: jupyterhub
      release: pangeohub
-     chart: jupyterhub-0.7.0
+     chart: jupyterhub-0.8.0
      heritage: Tiller
  spec:
    replicas: 1
    selector:
      matchLabels:
        component: hub
        app: jupyterhub
        release: pangeohub
    strategy:
      rollingUpdate: null
      type: Recreate
    template:
      metadata:
        labels:
          component: hub
          app: jupyterhub
          release: pangeohub
          hub.jupyter.org/network-access-proxy-api: "true"
          hub.jupyter.org/network-access-proxy-http: "true"
          hub.jupyter.org/network-access-singleuser: "true"
        annotations:
          # This lets us autorestart when the secret changes!
-         checksum/config-map: a0c51f62e57fea55d8e9c2eec8963633d202bebb720c39a76468d450d1db49b1
-         checksum/secret: 960e0816d076546363f7d8f04100eb4b9fe7bb71ce7ea9e47231dbaab0b04f28
-         prometheus.io/path: /hub/metrics
-         prometheus.io/scrape: "true"
+         checksum/config-map: 44414906e47e6cbf2d7d4f3b09fee9393333aa892b0629377e2ebb9adedff466
+         checksum/secret: 3630f83dbcfd21c86bcffa484af961ba0db4a93e02d53204cd6650f319dc8e5f
      spec:
        nodeSelector: {}
        affinity:
-         podAffinity:
+         nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
-             - weight: 1
-               podAffinityTerm:
-                 topologyKey: kubernetes.io/hostname
-                 labelSelector:
-                   matchExpressions:
-                     - key: component
-                       operator: In
-                       values: ['proxy']
-                     - key: release
-                       operator: In
-                       values: ["pangeohub"]
+             - weight: 100
+               preference:
+                 matchExpressions:
+                   - key: hub.jupyter.org/node-purpose
+                     operator: In
+                     values: [core]
        volumes:
          - name: config
            configMap:
              name: hub-config
          - name: secret
            secret:
              secretName: hub-secret
          - gitRepo:
              repository: https://github.com/pangeo-data/pangeo-custom-jupyterhub-templates.git
              revision: b09721bb1a1248dc115730d3c8a791600eae257e
            name: custom-templates
          - name: hub-db-dir
            persistentVolumeClaim:
              claimName: hub-db-dir
        serviceAccountName: hub
        securityContext:
          runAsUser: 1000
-         fsGroup: 1000
+         fsGroup: 1000  
        containers:
          - name: hub
-           image: jupyterhub/k8s-hub:0.7.0
+           image: jupyterhub/k8s-hub:0.8.0
            command:
              - jupyterhub
              - --config
              - /srv/jupyterhub_config.py
              - --upgrade-db
            volumeMounts:
              - mountPath: /etc/jupyterhub/config/
                name: config
              - mountPath: /etc/jupyterhub/secret/
                name: secret
              - mountPath: /usr/local/share/jupyterhub/custom_templates
                name: custom-templates
                subPath: pangeo-custom-jupyterhub-templates/templates
              - mountPath: /usr/local/share/jupyterhub/static/custom
                name: custom-templates
                subPath: pangeo-custom-jupyterhub-templates/assets
              - mountPath: /srv/jupyterhub
                name: hub-db-dir
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
            imagePullPolicy: IfNotPresent
            env:
-             - name: SINGLEUSER_IMAGE
-               value: "arokem/learning2learn:2019-05-21"
+             - name: PYTHONUNBUFFERED
+               value: "1"
+             - name: HELM_RELEASE_NAME
+               value: "pangeohub"
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: CONFIGPROXY_AUTH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: hub-secret
                    key: proxy.token
            ports:
              - containerPort: 8081
                name: hub
pangeo, daskkubernetes, Role (rbac.authorization.k8s.io) has changed:
  # Source: pangeo/templates/dask-kubernetes-rbac.yaml
  kind: Role
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: daskkubernetes
    namespace: pangeo
    labels:
-     chart: pangeo-v0.1.1-c02878a
+     chart: pangeo-19.03.05
      component: daskkubernetes
      heritage: Tiller
      release: pangeohub
  rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods/log"]
    verbs: ["get", "list"]
pangeo, hub, ServiceAccount (v1) has changed:
  # Source: pangeo/charts/jupyterhub/templates/hub/rbac.yaml
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: hub
    labels:
      component: hub
      app: jupyterhub
      release: pangeohub
-     chart: jupyterhub-0.7.0
+     chart: jupyterhub-0.8.0
      heritage: Tiller
pangeo, hub, RoleBinding (rbac.authorization.k8s.io) has changed:
  # Source: pangeo/charts/jupyterhub/templates/hub/rbac.yaml
  kind: RoleBinding
- apiVersion: rbac.authorization.k8s.io/v1beta1
+ apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: hub
    labels:
      component: hub
      app: jupyterhub
      release: pangeohub
-     chart: jupyterhub-0.7.0
+     chart: jupyterhub-0.8.0
      heritage: Tiller
  subjects:
    - kind: ServiceAccount
      name: hub
      namespace: pangeo
  roleRef:
    kind: Role
    name: hub
    apiGroup: rbac.authorization.k8s.io
pangeo, daskkubernetes, RoleBinding (rbac.authorization.k8s.io) has changed:
  # Source: pangeo/templates/dask-kubernetes-rbac.yaml
  kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: daskkubernetes
    namespace: pangeo
    labels:
-     chart: pangeo-v0.1.1-c02878a
+     chart: pangeo-19.03.05
      component: daskkubernetes
      heritage: Tiller
      release: pangeohub
  subjects:
  - kind: ServiceAccount
    name: daskkubernetes
  roleRef:
    kind: Role
    name: daskkubernetes
  apiGroup: rbac.authorization.k8s.io
pangeo, proxy, PodDisruptionBudget (policy) has changed:
  # Source: pangeo/charts/jupyterhub/templates/proxy/pdb.yaml
  apiVersion: policy/v1beta1
  kind: PodDisruptionBudget
  metadata:
    name: proxy
    labels:
      component: proxy
      app: jupyterhub
      release: pangeohub
-     chart: jupyterhub-0.7.0
+     chart: jupyterhub-0.8.0
      heritage: Tiller
  spec:
    minAvailable: 1
    selector:
      matchLabels:
        component: proxy
        app: jupyterhub
        release: pangeohub
pangeo, user-scheduler, PodDisruptionBudget (policy) has been added:
- 
+ # Source: pangeo/charts/jupyterhub/templates/scheduling/user-scheduler/pdb.yaml
+ apiVersion: policy/v1beta1
+ kind: PodDisruptionBudget
+ metadata:
+   name: user-scheduler
+   labels:
+     component: user-scheduler
+     app: jupyterhub
+     release: pangeohub
+     chart: jupyterhub-0.8.0
+     heritage: Tiller
+ spec:
+   minAvailable: 1
+   selector:
+     matchLabels:
+       component: user-scheduler
+       app: jupyterhub
+       release: pangeohub
pangeo, user-placeholder, StatefulSet (apps) has been added:
- 
+ # Source: pangeo/charts/jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml
+ apiVersion: apps/v1
+ kind: StatefulSet
+ metadata:
+   name: user-placeholder
+   labels:
+     component: user-placeholder
+     app: jupyterhub
+     release: pangeohub
+     chart: jupyterhub-0.8.0
+     heritage: Tiller
+ spec:
+   podManagementPolicy: Parallel
+   replicas: 0
+   selector:
+     matchLabels:
+       component: user-placeholder
+       app: jupyterhub
+       release: pangeohub
+   serviceName: "user-placeholder"
+   template:
+     metadata:
+       labels:
+         component: user-placeholder
+         app: jupyterhub
+         release: pangeohub
+     spec:
+       tolerations:
+         - key: hub.jupyter.org_dedicated
+           operator: Equal
+           value: user
+           effect: NoSchedule
+         - key: hub.jupyter.org/dedicated
+           operator: Equal
+           value: user
+           effect: NoSchedule
+       nodeSelector: {}
+       affinity:
+         nodeAffinity:
+           preferredDuringSchedulingIgnoredDuringExecution:
+             - weight: 100
+               preference:
+                 matchExpressions:
+                   - key: hub.jupyter.org/node-purpose
+                     operator: In
+                     values: [user]
+       terminationGracePeriodSeconds: 0
+       automountServiceAccountToken: false
+       containers:
+         - name: pause
+           image: gcr.io/google_containers/pause:3.0
+           resources:
+             requests:
+               cpu: 1
+               memory: 4G
+             limits:
+               cpu: 4
+               memory: 14G
pangeo, user-placeholder, PodDisruptionBudget (policy) has been added:
- 
+ # Source: pangeo/charts/jupyterhub/templates/scheduling/user-placeholder/pdb.yaml
+ apiVersion: policy/v1beta1
+ kind: PodDisruptionBudget
+ metadata:
+   name: user-placeholder
+   labels:
+     component: user-placeholder
+     app: jupyterhub
+     release: pangeohub
+     chart: jupyterhub-0.8.0
+     heritage: Tiller
+ spec:
+   minAvailable: 0
+   selector:
+     matchLabels:
+       component: user-placeholder
+       app: jupyterhub
+       release: pangeohub
```

Looks like quite a few changes!

**Comment by arokem** [comment]
A bit more information from today's experiments: I tore down everything and started fresh. This time, setting the helm chart version to `19.03.05` before starting, so that I would be using the most recent release of the helm chart. The thing started up fine, but when I tried to run the `4_upgrade_helm.sh` script, I got the same error as before (the python stack trace [here](https://github.com/pangeo-data/pangeo/issues/625#issuecomment-492709163)). This time, running `helm diff upgrade pangeohub pangeo/pangeo` gives me nothing (it's empty), so the maybe the helm diff is not helpful?

**Comment by arokem** [comment]
This comment seems like a hint in the right direction: https://github.com/jupyterhub/jupyterhub/issues/2075#issuecomment-413903550

Where and how is `jupyterhub upgrade-db` run?

**Comment by arokem** [comment]
OK. Ultimately this seems to be resolved by tearing the whole thing down, setting the helm chart version to `19.04.02-ef5490a` (which now pulls in the apparently necessary jupyterhub 0.9) and restarting.

**Comment by jhamman** [comment]
I think a good lesson here, at least while we're still iterating rapidly, is to update the chart regularly so we can pinpoint when/where changes need to be made.

Glad you got things working again @arokem
