### ISSUE TITLE
Pangeo failing all Helm versions > v0.1.1-e5fa7c4

### ISSUE THREAD

**Issue by Boes-man** [pangeo-data/pangeo#633]
Hello, I installed Pangeo 0.1.1-86665a6 via the cloud deploy process successfully. I have be testing 4_upgrade_helm.sh which works up to v0.1.1-e5fa7c4. Any version after this fails to deploy Pangeo. Initially versions complete the upgrade successfully but launching the server pod fails with "cant find singleuser" script. Latter versions fail to deploy completely as the hub pod can not start with a similar error about an OS env for singeluser.

Thanks

server/user pod error:
`Error: failed to start container "notebook": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"start-singleuser.sh\": executable file not found in $PATH": unknown
Back-off restarting failed container`

HUB Error:
`[E 2019-05-16 07:08:55.884 JupyterHub app:1623]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1620, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/lib/python3.6/types.py", line 204, in __next__
        return next(self.__wrapped)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1358, in initialize
        self.load_config_file(self.config_file)
      File "<decorator-gen-5>", line 2, in load_config_file
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 598, in load_config_file
        raise_config_file_errors=self.raise_config_file_errors,
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/usr/local/lib/python3.6/dist-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/srv/jupyterhub_config.py", line 46, in <module>
        c.KubeSpawner.singleuser_image_spec = os.environ['SINGLEUSER_IMAGE']
      File "/usr/lib/python3.6/os.py", line 669, in __getitem__
        raise KeyError(key) from None
    KeyError: 'SINGLEUSER_IMAGE'`

**Comment by arokem** [comment]
I definitely also saw this along the way in one of the permutations I went through in #625

**Comment by Boes-man** [comment]
**Current installed version** for this helm diff is, **0.1.1-86665a6**
Output from `helm diff upgrade pangeohub pangeo/pangeo **--version=v0.1.1-c02878a** -f secret_config.yaml -f jupyter_config.yaml` is below

`pangeo, daskkubernetes, RoleBinding (rbac.authorization.k8s.io) has changed:
  # Source: pangeo/templates/dask-kubernetes-rbac.yaml
  kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: daskkubernetes
    namespace: pangeo
    labels:
-     chart: pangeo-v0.1.1-86665a6
+     chart: pangeo-v0.1.1-c02878a
      component: daskkubernetes
      heritage: Tiller
      release: pangeohub
  subjects:
  - kind: ServiceAccount
    name: daskkubernetes
  roleRef:
    kind: Role
    name: daskkubernetes
  apiGroup: rbac.authorization.k8s.io
pangeo, hub, Deployment (apps) has changed:
  # Source: pangeo/charts/jupyterhub/templates/hub/deployment.yaml
  apiVersion: apps/v1beta2
  kind: Deployment
  metadata:
    name: hub
    labels:
      component: hub
      app: jupyterhub
      release: pangeohub
      chart: jupyterhub-0.7.0
      heritage: Tiller
  spec:
    replicas: 1
    selector:
      matchLabels:
        component: hub
        app: jupyterhub
        release: pangeohub
    strategy:
      rollingUpdate: null
      type: Recreate
    template:
      metadata:
        labels:
          component: hub
          app: jupyterhub
          release: pangeohub
          hub.jupyter.org/network-access-proxy-api: "true"
          hub.jupyter.org/network-access-proxy-http: "true"
          hub.jupyter.org/network-access-singleuser: "true"
        annotations:
          # This lets us autorestart when the secret changes!
          checksum/config-map: 6a22cb9314aee20a4f6974f2ecc0bdebdc05d32b4f7f0c77bccecc19c3825fca
          checksum/secret: 390bfdec696231824bcfee7e5d112c0bde0c2ed0227e7de51d8e5a8629e804fb
          prometheus.io/path: /hub/metrics
          prometheus.io/scrape: "true"
      spec:
        nodeSelector: {}
        affinity:
          podAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchExpressions:
                      - key: component
                        operator: In
                        values: ['proxy']
                      - key: release
                        operator: In
                        values: ["pangeohub"]
        volumes:
          - name: config
            configMap:
              name: hub-config
          - name: secret
            secret:
              secretName: hub-secret
          - emptyDir: {}
            name: custom-templates
          - name: hub-db-dir
            persistentVolumeClaim:
              claimName: hub-db-dir
        serviceAccountName: hub
        securityContext:
          runAsUser: 1000
          fsGroup: 1000
        containers:
          - name: hub
            image: jupyterhub/k8s-hub:v0.6
            command:
              - jupyterhub
              - --config
              - /srv/jupyterhub_config.py
              - --upgrade-db
            volumeMounts:
              - mountPath: /etc/jupyterhub/config/
                name: config
              - mountPath: /etc/jupyterhub/secret/
                name: secret
              - mountPath: /usr/local/share/jupyter/hub/custom_templates
                name: custom-templates
                subPath: pangeo-custom-jupyterhub-templates/templates
              - mountPath: /usr/local/share/jupyter/hub/static/custom
                name: custom-templates
                subPath: pangeo-custom-jupyterhub-templates/assets
              - mountPath: /srv/jupyterhub
                name: hub-db-dir
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
            imagePullPolicy: IfNotPresent
            env:
              - name: SINGLEUSER_IMAGE
-               value: "pangeo/notebook:86665a6"
+               value: "pangeo/base-notebook:2019.01.25"
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: CONFIGPROXY_AUTH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: hub-secret
                    key: proxy.token
            ports:
              - containerPort: 8081
                name: hub
pangeo, daskkubernetes, ServiceAccount (v1) has changed:
  # Source: pangeo/templates/dask-kubernetes-rbac.yaml
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: daskkubernetes
    namespace: pangeo
    labels:
-     chart: pangeo-v0.1.1-86665a6
+     chart: pangeo-v0.1.1-c02878a
      component: daskkubernetes
      heritage: Tiller
      release: pangeohub
pangeo, daskkubernetes, Role (rbac.authorization.k8s.io) has changed:
  # Source: pangeo/templates/dask-kubernetes-rbac.yaml
  kind: Role
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: daskkubernetes
    namespace: pangeo
    labels:
-     chart: pangeo-v0.1.1-86665a6
+     chart: pangeo-v0.1.1-c02878a
      component: daskkubernetes
      heritage: Tiller
      release: pangeohub
  rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods/log"]
    verbs: ["get", "list"]
`

**Comment by Boes-man** [comment]
Attaching diff outputs in files.
[helmdiff_0.1.1-86665a6_to_v0.1.1-c02878a.txt](https://github.com/pangeo-data/pangeo/files/3189560/helmdiff_0.1.1-86665a6_to_v0.1.1-c02878a.txt)
[helmdiff_0.1.1-86665a6_to_19.03.05.txt](https://github.com/pangeo-data/pangeo/files/3189561/helmdiff_0.1.1-86665a6_to_19.03.05.txt)
