### ISSUE TITLE
Zarr errors converting MUR SST NetCDF files to Zarr using Dask Kubernetes

### ISSUE THREAD

**Issue by abarciauskas-bgse** [pangeo-data/pangeo#637]
## Problem

I'm working on converting MUR SST NetCDF files (available via [PODAAC opendap](https://podaac-opendap.jpl.nasa.gov/opendap/allData/ghrsst/data/GDS2/L4/GLOB/JPL/MUR/v4.1/)) and running into an error:

```
ValueError: array not found at path 'analysed_sst'
```

## Setup

See [this gist](https://gist.github.com/abarciauskas-bgse/06bba856b9713fecabffed703f370667) for complete details.

* AWS cluster setup following https://zero-to-jupyterhub.readthedocs.io/en/latest/amazon/step-zero-aws-eks.html with 3 m4.2xlarge ec2 instances
* package versions installed on workers, scheduler, jupyter: zarr==2.3.1, dask==1.1.0, xarray==0.12.1
* dask config.yml:

```yaml
jupyter:
  name: jupyter
  env:
    - name: EXTRA_PIP_PACKAGES
      value: s3fs git+https://github.com/user/repo.git --upgrade
    - name: EXTRA_CONDA_PACKAGES
      value: numpy zarr netCDF4 xarray -c conda-forge --yes

worker:
  name: worker
  env:
    - name: EXTRA_PIP_PACKAGES
      value: s3fs git+https://github.com/user/repo.git --upgrade
    - name: EXTRA_CONDA_PACKAGES
      value: numpy zarr netCDF4 xarray -c conda-forge --yes

scheduler:
  name: scheduler
  env:
    - name: EXTRA_PIP_PACKAGES
      value: s3fs git+https://github.com/user/repo.git --upgrade
    - name: EXTRA_CONDA_PACKAGES
value: numpy zarr netCDF4 xarray -c conda-forge --yes
```
* core python code

```python
sst_netcdf = 'https://podaac-opendap.jpl.nasa.gov:443/opendap/allData/ghrsst/data/GDS2/L4/GLOB/JPL/MUR/v4.1/2002/152/20020601090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'
files = [ sst_netcdf ]
ds = xr.open_dataset(files[0], chunks={'time': 366, 'lat': 250, 'lon': 500})
compressor = zarr.Blosc(cname='zstd', clevel=5, shuffle=zarr.Blosc.AUTOSHUFFLE)
encoding = {v: {'compressor': compressor} for v in ds.data_vars}
ds.to_zarr('gmet.zarr', mode='w', encoding=encoding, consolidated=True)
```

Results in error:

```
ValueError: array not found at path 'analysed_sst'
```

With `kubectl logs <pod_name> returning:

```
distributed.protocol.pickle - INFO - Failed to deserialize b"\x80\x04\x95)\x01\x00\x00\x00\x00\x00\x00(\x8cj('open_dataset-14da59ad3c7124c49e6312dabf96e0a5analysis_error-c2f7cdee546615266b710e135ac15d48', 0, 42, 5)\x94\x8c\tzarr.core\x94\x8c\x05Array\x94\x93\x94)\x81\x94(\x8c\x0czarr.storage\x94\x8c\x0eDirectoryStore\x94\x93\x94)\x81\x94}\x94\x8c\x04path\x94\x8c\x16/home/jovyan/gmet.zarr\x94sb\x8c\x0eanalysis_error\x94\x89NN\x88\x88t\x94b\x8c\x08builtins\x94\x8c\x05slice\x94\x93\x94K\x00K\x01N\x87\x94R\x94h\x10M\x04)M\xfe)N\x87\x94R\x94h\x10M\xc4\tM\xb8\x0bN\x87\x94R\x94\x87\x94N\x89t\x94."
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/zarr/core.py", line 150, in _load_metadata_nosync
    meta_bytes = self._store[mkey]
  File "/opt/conda/lib/python3.7/site-packages/zarr/storage.py", line 728, in __getitem__
    raise KeyError(key)
KeyError: 'analysis_error/.zarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/opt/conda/lib/python3.7/site-packages/zarr/core.py", line 1943, in __setstate__
    self.__init__(*state)
  File "/opt/conda/lib/python3.7/site-packages/zarr/core.py", line 124, in __init__
    self._load_metadata()
  File "/opt/conda/lib/python3.7/site-packages/zarr/core.py", line 141, in _load_metadata
    self._load_metadata_nosync()
  File "/opt/conda/lib/python3.7/site-packages/zarr/core.py", line 152, in _load_metadata_nosync
    err_array_not_found(self._path)
  File "/opt/conda/lib/python3.7/site-packages/zarr/errors.py", line 25, in err_array_not_found
    raise ValueError('array not found at path %r' % path)
ValueError: array not found at path 'analysis_error'
distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/zarr/core.py", line 150, in _load_metadata_nosync
    meta_bytes = self._store[mkey]
  File "/opt/conda/lib/python3.7/site-packages/zarr/storage.py", line 728, in __getitem__
    raise KeyError(key)
KeyError: 'analysis_error/.zarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/worker.py", line 1078, in add_task
    self.tasks[key] = _deserialize(function, args, kwargs, task)
  File "/opt/conda/lib/python3.7/site-packages/distributed/worker.py", line 2693, in _deserialize
    args = pickle.loads(args)
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/opt/conda/lib/python3.7/site-packages/zarr/core.py", line 1943, in __setstate__
    self.__init__(*state)
  File "/opt/conda/lib/python3.7/site-packages/zarr/core.py", line 124, in __init__
    self._load_metadata()
  File "/opt/conda/lib/python3.7/site-packages/zarr/core.py", line 141, in _load_metadata
    self._load_metadata_nosync()
  File "/opt/conda/lib/python3.7/site-packages/zarr/core.py", line 152, in _load_metadata_nosync
    err_array_not_found(self._path)
  File "/opt/conda/lib/python3.7/site-packages/zarr/errors.py", line 25, in err_array_not_found
    raise ValueError('array not found at path %r' % path)
ValueError: array not found at path 'analysis_error'
```

Any advice is appreciated!

cc @jhamman

**Comment by rabernat** [comment]
You are trying to write the zarr dataset to a file, but it seems like the dask worker nodes don’t have access to a shared file system. You should try writing directly to S3.

**Comment by abarciauskas-bgse** [comment]
Correct! Thanks so much @rabernat. I kept running into this ValueError (using s3 as well) but this error is a red herring for user issues trying to write to a shared file system, which I was doing incorrectly either by trying to write to jupyter's local filesystem or trying to write to S3 without credentials properly set. Important to look at worker logs in these cases.

Have a pretty task graph now.
<img width="1434" alt="Screen Shot 2019-05-18 at 1 15 33 AM" src="https://user-images.githubusercontent.com/15016780/57964944-137bea80-790b-11e9-9f86-407cdf949cb2.png">
