### ISSUE TITLE
Hub crashed?

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#65]
I ran a computation that I think overwhelmed memory.  I was surprised that I was able to get the number of pods that I requested.  I suspect that my settings for resource limits aren't going through. 

As a result I believe that I crashed the hub.  This is coming out of the logs.

<details>

```
[E 2018-01-09 15:27:32.600 JupyterHub web:1590] Uncaught exception GET /hub/user/rabernat/api/terminals?1515511650879 (10.128.0.9)
    HTTPServerRequest(protocol='http', host='pangeo.pydata.org', method='GET', uri='/hub/user/rabernat/api/terminals?1515511650879', version='HTTP/1.1', remote_ip='10.128.0.9', headers={'Accept-Encoding': 'gzip, deflate', 'X-Original-Uri': '/hub/user/rabernat/api/terminals?1515511650879', 'Host': 'pangeo.pydata.org', 'X-Forwarded-Proto': 'http,http', 'Referer': 'http://pangeo.pydata.org/user/rabernat/lab?redirects=1', 'X-Forwarded-For': '10.128.0.9,10.20.2.21', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'X-Xsrftoken': '2|b3d9bd5d|63295a57e04c1313d4765875f74efe04|1515378485', 'Connection': 'close', 'X-Forwarded-Port': '80,80', 'X-Scheme': 'http', 'Accept-Language': 'en-US,en;q=0.9,it;q=0.8,fr;q=0.7,es;q=0.6', 'Cookie': 'jupyter-hub-token="2|1:0|10:1515378226|17:jupyter-hub-token|44:N2IyODA1MWIyYzNmNGQ4MTkyMjkxYTYyNDJiODQ5YjY=|54747c9e86066275a5f66d7050616080b706535f11f7bfbe47cc7487fc1e8521"; __cfduid=d83d872e9777cf3e6260825d4f0767b481504752535; _xsrf=2|b3d9bd5d|63295a57e04c1313d4765875f74efe04|1515378485; _ga=GA1.2.1231850512.1504790368; _gid=GA1.2.1410744416.1515445243', 'X-Real-Ip': '10.128.0.9', 'X-Forwarded-Host': 'pangeo.pydata.org'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 675, in get
        current_user = self.get_current_user()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 229, in get_current_user
        return self.get_current_user_cookie()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 222, in get_current_user_cookie
        return self._user_for_cookie(self.hub.cookie_name)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 206, in _user_for_cookie
        u = self.db.query(orm.User).filter(orm.User.cookie_id==cookie_id).first()
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2755, in first
        ret = list(self[0:1])
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
        return list(res)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
        return self._execute_and_instances(context)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2876, in _execute_and_instances
        close_with_result=True)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2885, in _get_bind_args
        **kw
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2867, in _connection_from_session
        conn = self.session.connection(**kw)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 1013, in connection
        execution_options=execution_options)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 1018, in _connection_for_bind
        engine, execution_options)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
        self._assert_active()
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
        % self._rollback_exception
    sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) disk I/O error [SQL: 'UPDATE users SET last_activity=? WHERE users.id = ?'] [parameters: ('2018-01-09 15:06:58.696000', 57)]
    
[E 2018-01-09 15:27:32.602 JupyterHub web:1038] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1036, in send_error
        self.write_error(status_code, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 631, in write_error
        html = self.render_template('%s.html' % status_code, **ns)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 582, in render_template
        ns.update(self.template_namespace)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 588, in template_namespace
        user = self.get_current_user()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 229, in get_current_user
        return self.get_current_user_cookie()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 222, in get_current_user_cookie
        return self._user_for_cookie(self.hub.cookie_name)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 206, in _user_for_cookie
        u = self.db.query(orm.User).filter(orm.User.cookie_id==cookie_id).first()
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2755, in first
        ret = list(self[0:1])
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
        return list(res)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
        return self._execute_and_instances(context)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2876, in _execute_and_instances
        close_with_result=True)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2885, in _get_bind_args
        **kw
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2867, in _connection_from_session
        conn = self.session.connection(**kw)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 1013, in connection
        execution_options=execution_options)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 1018, in _connection_for_bind
        engine, execution_options)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
        self._assert_active()
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
        % self._rollback_exception
    sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) disk I/O error [SQL: 'UPDATE users SET last_activity=? WHERE users.id = ?'] [parameters: ('2018-01-09 15:06:58.696000', 57)]
    
[E 2018-01-09 15:27:32.604 JupyterHub web:1518] Exception in exception handler
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1516, in _execute
        self._handle_request_exception(e)
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1570, in _handle_request_exception
        self.send_error(500, exc_info=sys.exc_info())
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1040, in send_error
        self.finish()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 105, in finish
        super().finish(*args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 993, in finish
        self._log()
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1540, in _log
        self.application.log_request(self)
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 2053, in log_request
        self.settings["log_function"](handler)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/log.py", line 90, in log_request
        user = handler.get_current_user()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 229, in get_current_user
        return self.get_current_user_cookie()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 222, in get_current_user_cookie
        return self._user_for_cookie(self.hub.cookie_name)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 206, in _user_for_cookie
        u = self.db.query(orm.User).filter(orm.User.cookie_id==cookie_id).first()
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2755, in first
        ret = list(self[0:1])
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
        return list(res)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
        return self._execute_and_instances(context)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2876, in _execute_and_instances
        close_with_result=True)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2885, in _get_bind_args
        **kw
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2867, in _connection_from_session
        conn = self.session.connection(**kw)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 1013, in connection
        execution_options=execution_options)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 1018, in _connection_for_bind
        engine, execution_options)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
        self._assert_active()
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
        % self._rollback_exception
    sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) disk I/O error [SQL: 'UPDATE users SET last_activity=? WHERE users.id = ?'] [parameters: ('2018-01-09 15:06:58.696000', 57)]
```

</details>

cc @yuvipanda

**Comment by mrocklin** [comment]
All `/hub` pages are no longer working.

**Comment by rabernat** [comment]
Really bad timing. I was about to give a demo to a bunch of people here at the NSF workshop.

Any way we can get it up again fast?

**Comment by mrocklin** [comment]
Sorry about that.  There is a video here: https://www.youtube.com/watch?v=rSOJKbfNBNk

Working on resetting the system.

**Comment by yuvipanda** [comment]
Deleting the hub pod should bring it back up in a minute.

**Comment by mrocklin** [comment]
Confirmed that it's back up and running.

**Comment by rabernat** [comment]
Thanks for fixing! My demo was a success!

**Comment by mrocklin** [comment]
Huzzah.  I encourage you to encourage others to use the system (with appropriate disclaimers)
