### ISSUE TITLE
ECCO4r3 data inaccessible on intake catalogue

### ISSUE THREAD

**Issue by erikvansebille** [pangeo-data/pangeo#774]
Following the code at https://catalog.pangeo.io/browse/master/ocean/ECCOv4r3/
```python
from intake import open_catalog

cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean.yaml")
ds  = cat["ECCOv4r3"].to_dask()
```
gives an error
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-57a892e42891> in <module>
      2 
      3 cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean.yaml")
----> 4 ds  = cat["ECCOv4r3"].to_dask()

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/intake_xarray/base.py in to_dask(self)
     67     def to_dask(self):
     68         """Return xarray object where variables are dask arrays"""
---> 69         return self.read_chunked()
     70 
     71     def close(self):

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/intake_xarray/base.py in read_chunked(self)
     42     def read_chunked(self):
     43         """Return xarray object (which will have chunks)"""
---> 44         self._load_metadata()
     45         return self._ds
     46 

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/intake/source/base.py in _load_metadata(self)
    115         """load metadata only if needed"""
    116         if self._schema is None:
--> 117             self._schema = self._get_schema()
    118             self.datashape = self._schema.datashape
    119             self.dtype = self._schema.dtype

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/intake_xarray/base.py in _get_schema(self)
     16 
     17         if self._ds is None:
---> 18             self._open_dataset()
     19 
     20             metadata = {

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/intake_xarray/xzarr.py in _open_dataset(self)
     29 
     30         self._mapper = get_mapper(self.urlpath, **self.storage_options)
---> 31         self._ds = xr.open_zarr(self._mapper, **self.kwargs)
     32 
     33     def close(self):

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/xarray/backends/zarr.py in open_zarr(store, group, synchronizer, chunks, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, consolidated, overwrite_encoded_chunks, **kwargs)
    595         synchronizer=synchronizer,
    596         group=group,
--> 597         consolidated=consolidated,
    598     )
    599     ds = maybe_decode_store(zarr_store)

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/xarray/backends/zarr.py in open_group(cls, store, mode, synchronizer, group, consolidated, consolidate_on_close)
    257         if consolidated:
    258             # TODO: an option to pass the metadata_key keyword
--> 259             zarr_group = zarr.open_consolidated(store, **open_kwargs)
    260         else:
    261             zarr_group = zarr.open_group(store, **open_kwargs)

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/zarr/convenience.py in open_consolidated(store, metadata_key, mode, **kwargs)
   1180 
   1181     # setup metadata sotre
-> 1182     meta_store = ConsolidatedMetadataStore(store, metadata_key=metadata_key)
   1183 
   1184     # pass through

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/zarr/storage.py in __init__(self, store, metadata_key)
   2455             d = store[metadata_key].decode()  # pragma: no cover
   2456         else:  # pragma: no cover
-> 2457             d = store[metadata_key]
   2458         meta = json_loads(d)
   2459 

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/fsspec/mapping.py in __getitem__(self, key, default)
     74         k = self._key_to_str(key)
     75         try:
---> 76             result = self.fs.cat(k)
     77         except FileNotFoundError:
     78             if default is not None:

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/gcsfs/core.py in cat(self, path)
    766         """ Simple one-shot get of file data """
    767         u2 = self.url(path)
--> 768         r = self._call("GET", u2)
    769         r.raise_for_status()
    770         if "X-Goog-Hash" in r.headers:

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/gcsfs/core.py in _call(self, method, path, *args, **kwargs)
    468                     timeout=self.requests_timeout,
    469                 )
--> 470                 validate_response(r, path)
    471                 break
    472             except (HttpError, RequestException, GoogleAuthError) as e:

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/gcsfs/core.py in validate_response(r, path)
    116             raise ProxyError()
    117         elif "invalid" in m:
--> 118             raise ValueError("Bad Request: %s\n%s" % (path, msg))
    119         elif error:
    120             raise HttpError(error)

ValueError: Bad Request: https://www.googleapis.com/download/storage/v1/b/pangeo-ecco-eccov4r3/o/eccov4r3%2F.zmetadata?alt=media
b'User project specified in the request is invalid.'
```

**Comment by rabernat** [comment]
Note to @charlesbluca - we should add this information on all requester-pays data in the catalog.

**Comment by erikvansebille** [comment]
Thanks for the quick response. I have now signed up for a free google cloud account, but still get the same error. I assumed that simply by being logged-in everything would work automatically, but apparently not. Is there a tutorial/documentation how I can then couple my account to the `intake` request?

**Comment by rabernat** [comment]
@martindurant - can you advise us on how to make intake recognize Erik's user project automatically?

**Comment by martindurant** [comment]
You probably need to sign in with the gcloud CLI and set set it to use default permissions or set the default project

**Comment by charlesbluca** [comment]
In my experience trying to get `to_dask()` to recognize a user's default project, I ended up using 

```gcloud auth application-default login```

To specify an account/project and then generate a JSON token that is automatically used to authenticate a user through GCSFS.

**Comment by rabernat** [comment]
I can confirm that, after running `gcloud auth application-default login`, I could open the data locally.

**Comment by erikvansebille** [comment]
Maybe I'm completely missing something, but after fixing the gauth error (thanks @charlesbluca!), I now get the following error with the script from the top of this Issue

```python
_call non-retriable exception: 
Traceback (most recent call last):
  File "/Users/erik/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/gcsfs/core.py", line 470, in _call
    validate_response(r, path)
  File "/Users/erik/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/gcsfs/core.py", line 122, in validate_response
    raise HttpError({"code": r.status_code})
gcsfs.utils.HttpError
---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
<ipython-input-3-57a892e42891> in <module>
      2 
      3 cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean.yaml")
----> 4 ds  = cat["ECCOv4r3"].to_dask()

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/intake_xarray/base.py in to_dask(self)
     67     def to_dask(self):
     68         """Return xarray object where variables are dask arrays"""
---> 69         return self.read_chunked()
     70 
     71     def close(self):

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/intake_xarray/base.py in read_chunked(self)
     42     def read_chunked(self):
     43         """Return xarray object (which will have chunks)"""
---> 44         self._load_metadata()
     45         return self._ds
     46 

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/intake/source/base.py in _load_metadata(self)
    115         """load metadata only if needed"""
    116         if self._schema is None:
--> 117             self._schema = self._get_schema()
    118             self.datashape = self._schema.datashape
    119             self.dtype = self._schema.dtype

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/intake_xarray/base.py in _get_schema(self)
     16 
     17         if self._ds is None:
---> 18             self._open_dataset()
     19 
     20             metadata = {

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/intake_xarray/xzarr.py in _open_dataset(self)
     29 
     30         self._mapper = get_mapper(self.urlpath, **self.storage_options)
---> 31         self._ds = xr.open_zarr(self._mapper, **self.kwargs)
     32 
     33     def close(self):

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/xarray/backends/zarr.py in open_zarr(store, group, synchronizer, chunks, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, consolidated, overwrite_encoded_chunks, **kwargs)
    595         synchronizer=synchronizer,
    596         group=group,
--> 597         consolidated=consolidated,
    598     )
    599     ds = maybe_decode_store(zarr_store)

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/xarray/backends/zarr.py in open_group(cls, store, mode, synchronizer, group, consolidated, consolidate_on_close)
    257         if consolidated:
    258             # TODO: an option to pass the metadata_key keyword
--> 259             zarr_group = zarr.open_consolidated(store, **open_kwargs)
    260         else:
    261             zarr_group = zarr.open_group(store, **open_kwargs)

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/zarr/convenience.py in open_consolidated(store, metadata_key, mode, **kwargs)
   1180 
   1181     # setup metadata sotre
-> 1182     meta_store = ConsolidatedMetadataStore(store, metadata_key=metadata_key)
   1183 
   1184     # pass through

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/zarr/storage.py in __init__(self, store, metadata_key)
   2455             d = store[metadata_key].decode()  # pragma: no cover
   2456         else:  # pragma: no cover
-> 2457             d = store[metadata_key]
   2458         meta = json_loads(d)
   2459 

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/fsspec/mapping.py in __getitem__(self, key, default)
     74         k = self._key_to_str(key)
     75         try:
---> 76             result = self.fs.cat(k)
     77         except FileNotFoundError:
     78             if default is not None:

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/gcsfs/core.py in cat(self, path)
    766         """ Simple one-shot get of file data """
    767         u2 = self.url(path)
--> 768         r = self._call("GET", u2)
    769         r.raise_for_status()
    770         if "X-Goog-Hash" in r.headers:

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/gcsfs/core.py in _call(self, method, path, *args, **kwargs)
    485                     continue
    486                 logger.exception("_call non-retriable exception: %s", e)
--> 487                 raise e
    488 
    489         return r

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/gcsfs/core.py in _call(self, method, path, *args, **kwargs)
    468                     timeout=self.requests_timeout,
    469                 )
--> 470                 validate_response(r, path)
    471                 break
    472             except (HttpError, RequestException, GoogleAuthError) as e:

~/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/gcsfs/core.py in validate_response(r, path)
    120             raise HttpError(error)
    121         elif r.status_code:
--> 122             raise HttpError({"code": r.status_code})
    123         else:
    124             raise RuntimeError(m)

HttpError: 
​
```

**Comment by rabernat** [comment]
@martindurant - any thoughts about this error?

**Comment by martindurant** [comment]
Hm, clearly more description of that exception would have been useful. Is doing a debug possible? For the future, it would be good to be verbose here, perhaps just `r.raise_for_status()`. As it is, any number of things might have gone wrong, though simple things like timeout ought to have been retried.
Sorry I can't be more helpful.

**Comment by erikvansebille** [comment]
I've pasted below the result of `print(r.__dict__)`
```python
{'_content': b'Bucket is requester pays bucket but no user project provided.', 
'_content_consumed': True, 
'_next': None, 
'status_code': 400, 
'headers': {'X-GUploader-UploadID': 'AAANsUm2wvwLSmBdOTHAolA1M91qiuPBrfmk0-IYqHLzR4Repu0D3tCBvdkOSiw25HKqIv5rL3952YDSL_XB6HUcEQq0wqQaSg', 
'Content-Type': 'text/html; charset=UTF-8', 
'Date': 'Fri, 01 May 2020 15:17:05 GMT', 
'Vary': 'Origin, X-Origin', 
'Expires': 'Fri, 01 May 2020 15:17:05 GMT', 
'Cache-Control': 
'private, max-age=0', 
'Content-Length': '61', 
'Server': 'UploadServer', 
'Alt-Svc': 'h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"'}, 
'raw': <urllib3.response.HTTPResponse object at 0x1233abda0>, 
'url': 'https://www.googleapis.com/download/storage/v1/b/pangeo-ecco-eccov4r3/o/eccov4r3%2F.zmetadata?alt=media', 
'encoding': 'UTF-8', 
'history': [], 
'reason': 'Bad Request', 
'cookies': <RequestsCookieJar[]>, 
'elapsed': datetime.timedelta(0, 0, 328407), 
'request': <PreparedRequest [GET]>, 
'connection': <requests.adapters.HTTPAdapter object at 0x1208607b8>}
```
Is that enough debug info?

By the way, I did also issue `gcloud auth application-default login`

**Comment by rabernat** [comment]
Erik, thanks for sticking with this! I appreciate your help debugging this issue!

Let's take intake out of the picture. Can you verify this code works for you?
```python
import gcsfs
import xarray as xr
gcs = gcsfs.GCSFileSystem(token='google_default', requester_pays=True)
url = 'gs://pangeo-ecco-eccov4r3/eccov4r3'
ds = xr.open_zarr(gcs.get_mapper(url), consolidated=True)
```

This works for me from my laptop at home. My gcsfs version is 0.3.0.

**Comment by martindurant** [comment]
> '_content': b'Bucket is requester pays bucket but no user project provided.'

The value of project is apparently still not getting through. It is also an argument to the gcsfs constructor, and can be set also with the environment variable GCSFS_DEFAULT_PROJECT

**Comment by erikvansebille** [comment]
Thanks @martindurant and @rabernat, I finally got this to work. It was a combination of not creating a project yet on Google Cloud and also a botched `gcloud auth login` procedure last week. So all problems on my end... Thanks for the support!
