### ISSUE TITLE
Can't reproduce pangeo galery exemple: RefreshError: ("Failed to retrieve http://metadata.google.internal...

### ISSUE THREAD

**Issue by dvictori** [pangeo-data/pangeo#917]
I'm learning how to use the Pangeo data stored on Google Cloud. So I'm trying to reproduce the code found in http://gallery.pangeo.io/repos/pangeo-gallery/cmip6/basic_search_and_load.html

I've setup a local Jupyter and when I try to show the contents of a dataset, nothing happens. I then placed the code in Google Colab and the same code now gives me a `TransportError` and `RefreshError`

This seams related to #148 but I could not find how the issue was fixed.

I've placed the code here:  
https://colab.research.google.com/drive/13XjNIKlxXvhPMR62laYmmgnir-sRqu8q?usp=sharing

And this is the full code and error

```python
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr
import zarr
import fsspec

%matplotlib inline
%config InlineBackend.figure_format = 'retina'
plt.rcParams['figure.figsize'] = 12, 6

df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv')
df_ta = df.query("activity_id=='CMIP' & table_id == 'Amon' & variable_id == 'tas' & experiment_id == 'historical'")
df_ta_ncar = df_ta.query('institution_id == "NCAR"')

# get the path to a specific zarr store (the first one from the dataframe above)
zstore = df_ta_ncar.zstore.values[-1]
print(zstore)

# create a mutable-mapping-style interface to the store
mapper = fsspec.get_mapper(zstore)

# open it using xarray and zarr
ds = xr.open_zarr(mapper, consolidated=True)
ds

# error ouput bellow this point

gs://cmip6/CMIP6/CMIP/NCAR/CESM2-FV2/historical/r2i1p1f1/Amon/tas/gn/v20200226/

ERROR:gcsfs:_request out of retries on exception: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7bddd3bdbe80>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 111, in refresh
    self._retrieve_info(request)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 87, in _retrieve_info
    info = _metadata.get_service_account_info(
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 234, in get_service_account_info
    return get(request, path, params={"recursive": "true"})
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/_metadata.py", line 182, in get
    raise exceptions.TransportError(
google.auth.exceptions.TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7bddd3bdbe80>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/retry.py", line 114, in retry_request
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/core.py", line 414, in _request
    headers=self._get_headers(headers),
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/core.py", line 393, in _get_headers
    self.credentials.apply(out)
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/credentials.py", line 187, in apply
    self.maybe_refresh()
  File "/usr/local/lib/python3.10/dist-packages/gcsfs/credentials.py", line 182, in maybe_refresh
    self.credentials.refresh(req)
  File "/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py", line 117, in refresh
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
google.auth.exceptions.RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7bddd3bdbe80>)

---------------------------------------------------------------------------

TransportError                            Traceback (most recent call last)

[/usr/local/lib/python3.10/dist-packages/google/auth/compute_engine/credentials.py](https://localhost:8080/#) in refresh(self, request)
    110         try:
--> 111             self._retrieve_info(request)
    112             self.token, self.expiry = _metadata.get_service_account_token(

26 frames

TransportError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7bddd3bdbe80>)


The above exception was the direct cause of the following exception:

RefreshError                              Traceback (most recent call last)

<decorator-gen-119> in _request(self, method, path, headers, json, data, *args, **kwargs)

/usr/local/lib/python3.10/dist-packages/six.py in raise_from(value, from_value)

RefreshError: ("Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Engine metadata service. Status: 404 Response:\nb''", <google.auth.transport.requests._Response object at 0x7bddd3bdbe80>)
```

**Comment by dvictori** [comment]
Found out that I need to use `fs = gcsfs.GCSFileSystem(token='anon')` in order to access the public data. So cell 5 in the Python notebook should be:

```python
zstore = df_ta_ncar.zstore.values[-1]
print(zstore)

# create a mutable-mapping-style interface to the store

fs = gcsfs.GCSFileSystem(token='anon')
mapper = fs.get_mapper(zstore)

# open it using xarray and zarr
ds = xr.open_zarr(mapper, consolidated=True)
ds
```

**Comment by jhamman** [comment]
Hi @dvictori  - I'm sorry no one ever responded here. Most discussions like this have moved to the pangeo discourse forum now (https://discourse.pangeo.io/). If this is still an issue for you, I suggest asking your question there.
